gamecon-cz/gamecon

- admin/scripts/modules/uvod.xtpl
Toto je moje první zkouška pull requestu. Není tu moc co na review.
> Oprava Statut na Status

- model/novinka.php
- web/sablony/blog.xtpl
- web/soubory/styl/styl.less
> Výpis autora a data vydání u blogového příspěvku

- nastaveni/nastaveni.php
> nastavení triggers pro 2017

- web/sablony/titulka.xtpl
Opravu je potřeba spojit s nahráním nových obrázků.
> oprava šablony titulky pro přidání nových obrázků androdidů

- migrace/016.php
- web/tridy/menu.php
> Přidání ParConu do menu a do linií

- web/moduly/finance.php
- web/sablony/prihlaska.xtpl
- web/soubory/styl/styl.less
Prosím o review (např. styl mne zajímá jestli je ok z tvého pohledu)
> Úprava datumů v přihlášce a financích

- web/sablony/index.xtpl
> Úprava linku a náhledu na video

- nastaveni/nastaveni.php
- web/moduly/finance.php
Prosím o review a příp. merge. Obecně jsem se snažil vše otestovat - tzn. zčeknul jsem jak chování po nastavení země, tak chování po připsání platby (připsal jsem si ručně přes DB) a mělo by to být ok.
Jediná taková "pochybnost" je Poznámka pro příjemce - IBAN a SWIFT je v konstantách, ale poznámka pro příjemce v kódu. Přišlo mi podivné dávat do konstant hodnotu "/VS/".
> Oprava plateb - slováci

- migrace/019.php
- model/cenik.php
- nastaveni/nastaveni.php
> Nedělní noc zdarma

- admin/scripts/modules/finance/slucovani.php
- admin/scripts/modules/finance/slucovani.xtpl
- model/date-time-cz.php
- model/finance.php
- model/uzivatel-slucovani.php
- model/uzivatel.php
- web/moduly/registrace.php
Rozšířil jsem slučování o další hodnoty a odstranil volbu id. Vždy se provede sloučení na nižší id. Prosím o důkladnější kontrolu funkčnosti i když jsem provedl testy avypadalo to OKm, je možné, že jsem zbořil nějakou bábovičku, o které nevím.
> Rozšíření slučovaní uživatelů v adminu o další hodnoty

- nastaveni/nastaveni.php
> Zadatí datumů do nastaveni.php + úprava kurzu eura

- admin/scripts/modules/uvod.php
- model/funkce/fw-database.php
…orce.
Nakonec jsem nevycházel z té Rájové větve, protože to házelo jedno výjimku za druhou a spálil bych na tom víc času než na samotné úpravě.
Mrkni na to hození výjimky. Není to úplně čisté - nikde to necheckuje, že je to opravdu doublovaná přezdívka, ale pro tuto úpravu bych nejspíš musel dělat úpravy v modelu a tím by se výrazně zvýšila náročnost.
> Možnost změnit přezdívku v adminu

- model/aktivita.php
- model/editor.xtpl
> Úprava délky krátké anotace

- web/tridy/menu.php
> Odstranění "English Program" z hlavního menu

- web/soubory/styl/styl.less
Odmazání ročníku u obrázku pozadí.
> Obrazek_pozadi

- model/shop-ubytovani.php
- model/shop-ubytovani.xtpl
- web/sablony/prihlaska.xtpl
https://trello.com/c/d1LCG2YP/597-1-d%C3%A9lka-znak%C5%AF-ve-v%C3%BDpisu-ubytov%C3%A1n%C3%AD
> zobrazení delších názvů ubytování v přihlášce

- admin/scripts/zvlastni/program-uzivatele.php
https://trello.com/c/xDfxcu8i/634-program-osobn%C3%AD-prohozen%C3%AD-odkaz%C5%AF
> prohození odkazů v adminu v programu

- nastaveni/nastaveni.php
> Oprava dat pro zaplacení dle karty Zadat data do systému

- admin/scripts/modules/finance/slucovani.xtpl
- admin/scripts/modules/uvod.php
- admin/scripts/zvlastni/reporty/ubytovani.php
- composer.json
- composer.lock
- dokumentace/ostatni.md
- migrace/034.php
- model/sifrovatko.php
- model/uzivatel.php
- nastaveni/nastaveni-local-default.php
Šifrování jsem popsal do `dokumentace/ostatni.md`
> Šifrování občanek uživatelů v databázi

- admin/scripts/modules/uvod.xtpl
https://trello.com/c/m1vkxFX3/697-u-pozn%C3%A1mky-odjel-z-gc-text-o-nov%C3%A1%C4%8Dc%C3%ADch
> Odstranění informace o nováčcích v nápovědách

- model/aktivita.php
- nastaveni/nastaveni.php
https://trello.com/c/xOWnk3Nd/691-1-p%C5%99ejmenov%C3%A1n%C3%AD-n%C3%A1hradn%C3%ADk%C5%AF
> Přejmenování přihlašování náhradníků

- model/program.php
https://trello.com/c/lskvYPIp/724-m%C5%AFj-program-v2
> Seskupený můj program podle dne

- admin/scripts/modules/statistiky.php
- nastaveni/nastaveni.php
- web/sablony/prihlaska.xtpl
https://trello.com/c/nGfEacem/679-p%C5%99eklopen%C3%AD-webu-na-nov%C3%BD-ro%C4%8Dn%C3%ADk
> Překlopení ročníku

- migrace/048.php
SQL migrace na smazání OP z DB, viz https://trello.com/c/Ah269mDu/700-1-smaz%C3%A1n%C3%AD-op-z-adminu
> Smazani cisel obcanskych prukazu z DB

- model/program.php
https://trello.com/c/NdteZ2N4/757-nefunguje-spr%C3%A1vn%C4%9B-m%C5%AFj-program
> Oprava nezobrazení přihlášené první aktivity dne

- composer.json
- web/moduly/registrace.php
Testoval jsem to jen na své anonymizované databázi, kde by sice měl být stejný počet loginů, ale zas mají dost jednoduché názvy. Otestuj to prosím na betě.
> Dlouhy seznam obsazenych loginu nezhrouti javascript na registraci

- admin/files/design/styl.css
- admin/scripts/modules/uvod.php
- admin/scripts/modules/uvod.xtpl
- composer.json
- migrace/050.php
- migrace/051.php
- model/date-time-cz.php
- model/funkce/funkce.php
- model/uzivatel.php
Potvrzení je ukládáno jako `Date`, abychom příští rok poznali, že už neplatí a požádali o další.
Přidán také quick report, který vrátí všechny účastníky mladší patnácti let. Ti bez potvrzení nahoře, ti s potvrzením dole (nechal jsem je tam pro kontrolu, že nikdo nechybí).
Počítáme s věkem uživatele v den začátku gameconu, což je datum z konstanty.
https://trello.com/c/TmZB5o0B/756-zkontrolovat-pozn%C3%A1mky-pro-15-let
> Potvrzeni zakonneho zastupce

- composer.json
- migrace/000.php
- model/db-object.php
- model/novinka.php
- model/stranka.php
- nastaveni/db-migrace.php
- nastaveni/zavadec-zaklad.php
- nastaveni/zavadec.php
- web/moduly/program.php
- web/moduly/titulka.php
- web/sablony/titulka.xtpl
- web/tridy/modul.php
Pokud databáze neexistuje a Gamecon běží lokálně, tak se databáze vytvoří. Frontend naběhne i s prázdnou databází.
Poznámka: museli jsme tam přidat obezličku s prázdnou novinkou, protože současné šablony neumí `if` a rozšiřovat šablonovací engine nechceme, raději ho nahradíme.
https://trello.com/c/3TiprMtl/747-2-pr%C3%A1zdn%C3%A1-datab%C3%A1ze-v2
> Gamecon lze pustit i bez databaze

- web/index.php
- web/moduly/program.php
- web/soubory/program-skryvani-linii.js
- web/soubory/styl/program-skryvani-linii.less
Javascript filtr na zobrazení linií v programu.
Předběžně jsem informoval Barču a Shaka, že bych chtěl tuto funkci dodělat, a prý ok. Posílám teda PR. Narazil jsem trochu na problém, že javascripty a styly jsou v .gitignore, tzn. nešlo úplně snadno je commitnou, ale nakonec se to nějak podařilo. Snad je to teda i správně stáhne při fetchnutí repozitáře. Minimálně v diffu se zdá, že jsou.
Screenshot:
> možnost filtrace programu podle linií

- admin/files/query-do-odkazu-submenu.js
- admin/scripts/modules/prezence/_casy.php
- admin/scripts/modules/prezence/_casy.xtpl
- admin/scripts/modules/prezence/prezence.php
- admin/scripts/modules/prezence/prezence.xtpl
- admin/scripts/modules/prezence/tisk.xtpl
- admin/scripts/zvlastni/last-minute-tabule.php
- admin/templates/main.xtpl
- model/aktivita.php
- model/date-time-cz.php
- model/uzivatel.php
https://trello.com/c/3FV6MP7N/779-v-prezenci-a-tisku-zobrazovat-jen-%C4%8Dasy-s-aktivitami
V Prezenci a jejím tisku se zobrazují ve filtru jen ty časy, ve kterých se něco děje - je v nich nějaká aktivita.
> Jen aktivni casy v prezenci

- admin/scripts/modules/uvod.php
- admin/scripts/modules/uvod.xtpl
Vyřešeno přes javascript confirm, jak jsou v adminu zvyklí.
https://trello.com/c/TmZB5o0B/756-zkontrolovat-pozn%C3%A1mky-pro-15-let
> Nutne potrvzeni pri ukladani uzivatele s chybejicim potvrenim od dospele osoby

- admin/scripts/modules/uvod.php
- admin/scripts/modules/uvod.xtpl
Admini potřebují občas opravit pohlaví uživatele https://trello.com/c/LMovvQif/785-chyba-v-p%C5%99ihla%C5%A1ov%C3%A1n%C3%AD-%C5%BEensk%C3%A1-mu%C5%BEsk%C3%A1-m%C3%ADsta
> Pohlavi uzivatele lze editovat v adminu

- admin/scripts/modules/uvod.php
- admin/scripts/modules/uvod.xtpl
Behem Gameconu vyskakuje pri ukoncovani prace s uzivatelem upozorneni take pri chybejicim potvrzeni od rodicu.
https://trello.com/c/TmZB5o0B/756-zkontrolovat-pozn%C3%A1mky-pro-15-let
> Rozsireno upozorneni pri ukoncovani prace s uzivatelem

- admin/index.php
- admin/scripts/admin-menu.php
- admin/scripts/modules/finance/_paticka.php
- admin/scripts/modules/finance/_paticka.xtpl
Náhled jak to vypadá:\
https://trello.com/c/yxtXNTjE/791-finance-neznaj%C3%AD-nastaven%C3%BD-kurz-%E2%82%AC
> Finance vidi dole na strance pouzity kurz eura

- web/moduly/registrace.php
- web/soubory/styl/styl.less
Neprozrazujeme loginy ve zdrojovém kódu stránky s registrací.
Datum se před odesláním validuje přes PHP, abychom odchytili vzácné případy, kdy se formát zdá být v pořádku, ale není a v PHP by to padlo na fatal.
https://trello.com/c/HTwUQc7R/762-bezpe%C4%8Dnost%C3%AD-probl%C3%A9m-ve%C5%99ejn%C3%A9-loginy-a-emaily
> Neprozrazujeme loginy ve zdrojovem kodu registrace

- admin/scripts/modules/uvod.php
- admin/scripts/modules/uvod.xtpl
Zapomněl jsem ošetřit situaci, kdy uživatel nepotřebuje potvrzení od rodičů, což pak chybí v javascriptu a pak nám z toho vznikne nevalidní a hlavně nefunkční javascript na stránce Úvod v adminu.
https://trello.com/c/4gPOeUar/794-nelze-p%C5%99ihl%C3%A1sit-u%C5%BEivatele-na-gamecon-z-adminu
> Javascript nepadne na chybu kdyz uzivatel nema potvrzeni od rodicu

- admin/index.php
Díky za ten hotfix.
Zjedodušil bych to takhle, kdy se kontroluje existence submenu, ať už se vzalo kde se vzalo.
> Zjednodusena podminka pro kontrolu submenu v adminu

- model/editor.xtpl
Přidal jsem filtr podle jména do Admin -> Aktivity -> Nová aktivita
https://trello.com/c/p7IMJZek/748-zm%C4%9Bnit-pole-zad%C3%A1n%C3%AD-vyprav%C4%9B%C4%8De-u-aktivity
> Organizator pro novou aktivitu muze byt filtrovan podle prezdivky

- composer.json
- nastaveni/initial-fatal-error-handler.php
- nastaveni/nastaveni-local-default.php
- nastaveni/nastaveni-vychozi.php
- nastaveni/nastaveni.php
- nastaveni/zavadec.php
https://trello.com/c/Pcw5vgF9/778-z%C5%99ejm%C4%9B-v-produkci-zobrazujeme-stack-trace-p%C5%99i-chyb%C4%9B-cht%C4%9Blo-by-to-p%C4%9Bknou-chybovou-str%C3%A1nku
Testoval jsem na situace, kdy ještě před nahozením Výjimkovače (Tracy)
- se nešlo připojit k databázi (smazal jsem heslo k databázi)
- dříve to ukázalo stack trace, teď se při vývoji ukáže Výjimkovač (Tracy) a v produkci hezká error stránka
- nešlo kód zparsovat (E_PARSE)
- vyskočila základní výjimka \Exception
- padlo to na programátorem vypuštěný error E_USER_ERROR
Navíc jsem potlačil notice při definování úvodních konstant, protože je definujeme několikrát a když má někdo zapnutý reporting všeho, tak mu Gamecon ani nenaběhne kvůli `session_start(): Cannot start session when headers already sent`
> Error stack trace is not shown even if happens before Tracy handler

- admin/scripts/zvlastni/reporty/aktivity.php
- model/aktivita.php
https://trello.com/c/kHyYs4CJ/821-jak-funguje-report-historie-aktivit
Kluci z finančního potřebují trochu provětrat report aktivit, aby z něj snáze poznali, kolik lidí na aktivitu nakonec opravdu dorazilo, jaké bonusy dostali vypravěči a kdo ti vypravěči vlastně jsou.
> 821 jak funguje report historie aktivit

- admin/scripts/modules/finance/slucovani.xtpl
https://trello.com/c/VCrhylvO/835-oprava-slu%C4%8Dov%C3%A1n%C3%AD-profil%C5%AF
Opraven fatal při slučování profilů - volání přejmenované metody.
> Fixed crash on merge of duplicated accounts

- admin/scripts/zvlastni/reporty/celkovy-report.php
- model/report.php
https://trello.com/c/bWgMzs5m/831-p%C5%99idat-pozn%C3%A1mka-do-bfgr
V celkovém reportu (BFGR) chyběla pro finance důležitá *poznámka* u uživatele. Přidal jsem ji nakonec za přehled nákupů.
> 831 přidat poznámka do bfgr

- model/vyjimkovac-omluva.xtpl
https://trello.com/c/GU2Ekcrz/833-poladit-text-na-chybov%C3%A9-str%C3%A1nce
S Bárou jsme trochu poladili text omluvy, kterou ukážeme při fatalu. Hlavní myšlenka byla, že chceme odkaz na Facebook jako první, protože je šance, že tam se návštěvník dočká odpovědi rychleji a ještě tam už možná info o chybě bude vyvěšené.
Mail byl přeřazen na druhou kolej.
> Apology about error is a little bit more readable

- admin/scripts/zvlastni/reporty/aktivity.php
https://trello.com/c/kHyYs4CJ/821-jak-funguje-report-historie-aktivit
Pavel potřebuje do Reportu historie aktivit přidat ještě info, zda je aktivita bez slev a zda je teamová.
> Pridano bez slevy a teamova k reportu historie aktivit

- migrace/061.php
- model/uzivatel-slucovani.php
https://trello.com/c/VCrhylvO/835-oprava-slučování-profilů
```
Cannot delete or update a parent row: a foreign key constraint fails (`d16779_gamecon`.`r_uzivatele_zidle`, CONSTRAINT `r_uzivatele_zidle_ibfk_1` FOREIGN KEY (`id_uzivatele`) REFERENCES `uzivatele_hodnoty` (`id_uzivatele`)) caused by DELETE FROM `uzivatele_hodnoty` WHERE `id_uzivatele` = "428"
```
Byla chyba při mazání uživatelského profilu, kde to zablokoval cizí klíč z tabulky `r_uzivatele_zidle`
> Fixed deleting a user on profile merging

- .github/workflows/run-tests.yml
- migrace/001.php
- model/funkce/fw-database.php
- nastaveni/nastaveni-local-default.php
- testy/AktivitaTagyTest.php
- testy/_zavadec.php
~WIP, nemergeovat prosím~ Done, hoď prosím review pokud chceš @jaroslavtyc a případně "rebase and merge".
Přidal jsem workflow, aby se pouštěly testy aspoň na Githubu, pokud jsou teď zakomentované pro vývoj lokálně.
Taky jsem opravil padající test. Vyplynulo z něj, že tabulky `sjednocene_tagy` a `kategorie_sjednocenych_tagu` mají sice nullable cizí klíč, ale při načítání je tam tvrdý join a štítky bez kategorie se tudíž uloží, ale už nenačtou. Dalo by se jedno či druhé opravit.
> Testy pomocí Github actions

- admin/scripts/modules/aktivity/aktivity.php
Aktivita nemusí mít místnost a kód pak hází notice (což vadí puristům jako jsem já.-)
> Oprava notice u aktivity bez lokace

- admin/scripts/zvlastni/program-uzivatele.php
- admin/templates/main.xtpl
Z úkolu https://trello.com/c/0EysD9VB/608-%C5%99azen%C3%AD-%C5%A1t%C3%ADtk%C5%AF je překlep v CSS a JS cestě k Jquery UI knihovně v aminu
> Oprava cest k jquery UI

- readme.md
první pul request, doufám že příště už to bude bez těch zmatků
změněn jen readme.md ale to si asi dohledáte
> update popisu instalace wampu

- readme.md
rozšíření pull requestu v gitu (o trello a nastaveni reviewer)
> Aktualizace readme.md pro nováčky podruhé

- model/cenik.php
- nastaveni/nastaveni.php
řešení drobné úpravy - viz komentář karty https://trello.com/c/KpcGwphn
> Konstanta modre triko zdarma

- model/finance.php
https://trello.com/c/oq6Kr7fX/829-zm%C4%9Bnit-bonusy-vyprav%C4%9B%C4%8D%C5%AFm
Zvýšeny bonusy vypravěčům.
> 829: Zvýšeny bonusy vypravěčům na rok 2021

- admin/scripts/modules/prava.php
- migrace/067.php
- model/Pravo.php
- model/funkce/funkce.php
- tests/funkce/FunkceTest.php
https://trello.com/c/KpcGwphn/579-nastavení-konstanty-pro-trička
Aby v názvu práva k tričku zdarma byla aktuální cena trička.
> 579: Název práva pro tričko zdarma navždy s cenou trička

- admin/index.php
- admin/scripts/prihlaseni.php
- admin/templates/operator.xtpl
- model/uzivatel.php
- nastaveni/nastaveni.php
https://trello.com/c/l36ZP35L/831-p%C5%99ihl%C3%A1sit-se-jako
> 831: Vybraní uživatelé se mohou přepnout na účet někoho jiného

- model/program.php
- model/uzivatel.php
- web/moduly/program-k-tisku.php
- web/moduly/program.php
- web/tridy/modul.php
https://trello.com/c/8cn7xKHQ/811-program-m%C5%AFj-program-pdf-neukazuje-veden%C3%A9-aktivity
> 811: V PDF přehledu aktivit se zobrazuje nick místo jména

- admin/scripts/modules/aktivity/prihlaseni-drd.php
Jenom zmáčknutý autoformát u prihlaseni-drd.php
> 804 autoformat prihlaseni drd

- model/shop-ubytovani.xtpl
https://trello.com/c/Uxmm2f8V/802-p%C5%99edm%C4%9Bty-v-shopu-2021
> Povolit ubytování jen v jednom druhu pokoje, ne různé pokoje na různé dny.
> 802: Povolit jen jeden druh pokoje při objednávání ubytování

- migrace/068.php
https://trello.com/c/Nm5I8ThV/804-prov%C3%A1z%C3%A1n%C3%AD-mdrd-a-lkd-a-wg
Pyramida aktivit.
> 804: Provázání MDrD a LKD a WG pro 2021

- model/shop-ubytovani.xtpl
https://trello.com/c/Uxmm2f8V/802-p%C5%99edm%C4%9Bty-v-shopu-2021#comment-60a37d191152c7521e070c82
> 802: Neměnit ručně vybrané Žádné ubytování při přepínání mezi volným ubytováním

- web/moduly/program.php
Ahoj, jdu snad trochu pomoct.
- v Editaci stranky je nyni pridan `<style>.program_legenda, .legenda { display: none; }}}</style>`
> feat: zobrazeni legendy nad programem, zatim jen nacteni, stylovani pozdeji

- model/program.php
- web/soubory/blackarrow/program/program-trida.css
https://trello.com/c/372DdDh3/814-program-color-coding
Jiné barvy pro aktivity v programu podle stavu, vypravěče a tak
> 814: Upraveny barvy pro legendu programu

- model/shop-ubytovani.php
- model/shop-ubytovani.xtpl
https://trello.com/c/IbiIHSA2/836-povolit-ubytov%C3%A1n%C3%AD-jen-v-jednom-druhu-pokoje
Chybně jsem podezíral Godrica, že zapomněl povolit změnu toho ubytování, které si uživatel objednal a zároveň se od té doby vyprodalo.
Chyba byla v mém javascriptu, který si měl zapamatovat poslední ručně vybrané ubytování pro každý den, jenže si to zapamatoval jen pro konkrétní pokoj, takže při výběru jiného pokoje v tom samém dni už skript nevěděl, co je opravdu naposledy vybrané ubytování.
> 802: Opraven javascript na povolení jen jednoho typu pokoje

- model/Cas/DateTimeGamecon.php
- model/program.php
- nastaveni/nastaveni.php
- web/moduly/program.php
Měli jsme nastavený začátek na 15. 7. 2021, jenže to je čtvrtek a technické aktivity začínají už ve středu.
> 841 chybí středa

- web/moduly/aktivity.php
kdyz je aktivita v instanci, ma nastaveno `patriPod`, takze se pak zobrazuje v jejich terminech vicero terminu... a ted i s Vypravecovo jmenem.
> feat: parsuj terminy a zobraz vypravece pokud aktivita patriPod

- admin/scripts/modules/aktivity/prihlaseni-drd.php
- model/Cas/DateTimeGamecon.php
- model/program.php
- nastaveni/nastaveni.php
- web/moduly/aktivity.php
- web/moduly/program.php
> je možné, že stránka (https://admin.gamecon.cz/aktivity/prihlaseni-drd), kde se dělalo odhlašování družin na mDrD háže Picarda kvůli tomu, že ještě nezačal  GC?
> Fix admin prihlaseni drd pro aktivity zdarma

- migrace/069.php
https://trello.com/c/iKKZHRsF/847-nefunguje-ubytovac%C3%AD-report
Tohle je následek naší čistky reportů - systému se nelíbí, že si někdo chce zobrazit report, který není v seznamu.
> 847: Ubytovací report přidán do databáze aby nepadal při použití

- admin/scripts/modules/aktivity/_editor-tagu.php
- admin/scripts/modules/aktivity/tagy.php
- model/aktivita.php
- model/editor-aktivity.xtpl
https://trello.com/c/ewoObSEp/858-sp%C3%A1rov%C3%A1n%C3%AD-lkd-do-2-vlny
Aby šlo v adminu párovat navazující aktivity.
> 858: Možnost spárovat aktivity

- nastaveni/nastaveni.php
- nastaveni/zavadec-zaklad.php
https://trello.com/c/LWhIUUuD/860-p%C5%99ihl%C3%A1%C5%A1en%C3%AD-z-webu-neplat%C3%AD-pro-admin
Aby session cookie platila i pro subdomény.
> 860: Rozšíření platnosti session cookie i pro subdomény

- admin/scripts/modules/web/editace-stranek.php
- admin/scripts/modules/web/editace-stranek.xtpl
- model/db-object.php
https://trello.com/c/7rlArhJY/863-web-celohry
Aby šlo přidávat nové stránky z adminu
> 863: Z adminu mohou být přidávány další stránky

- admin/scripts/zvlastni/reporty/aktivity.php
- admin/scripts/zvlastni/reporty/anketa.php
- admin/scripts/zvlastni/reporty/celkovy-report.php
- admin/scripts/zvlastni/reporty/duplicity.php
- admin/scripts/zvlastni/reporty/grafy-ankety.php
- admin/scripts/zvlastni/reporty/maily-dle-data-ucasti.php
- admin/scripts/zvlastni/reporty/maily-neprihlaseni.php
- admin/scripts/zvlastni/reporty/maily-prihlaseni.php
- admin/scripts/zvlastni/reporty/maily-vypraveci.php
- admin/scripts/zvlastni/reporty/neprihlaseni-vypraveci.php
- admin/scripts/zvlastni/reporty/parovani-ankety.php
- admin/scripts/zvlastni/reporty/pocty-her-graf.php
- admin/scripts/zvlastni/reporty/pocty-her.php
- admin/scripts/zvlastni/reporty/rozesilani-ankety.php
- admin/scripts/zvlastni/reporty/stravenky.php
- admin/scripts/zvlastni/reporty/ubytovani.php
- admin/scripts/zvlastni/reporty/update-zustatku.php
- model/report.php
https://trello.com/c/LVr1hY0o/850-%C3%BAprava-bfgr-reportu
V poznámkách k objednávkám se nám začalo objevovat HTML, což je naprd v CSV reportu, který Gandalg parsuje v Excelu přes svá magická makra.
> 850 úprava bfgr reportu

- admin/scripts/modules/reporty/reporty.xtpl
- migrace/070.php
https://trello.com/c/LVr1hY0o/850-%C3%BAprava-bfgr-reportu
Jelikož Celkovému reportu beztak nikdo neřekne jinak, než BFGR, tak přišla doba, abychom ten název přijali za oficiální.
> 850: Přiznání skutečného názvu největšímu reportu všech dob

- Dockerfile
- composer.json
- model/fio-platba.php
- model/platby.php
- tests/Model/FioPlatbaTest.php
https://trello.com/c/eA8cuhpM/168-api-sp%C3%A1rov%C3%A1n%C3%AD-sk-plateb-odchoz%C3%AD-platby
Platby se Slovenska občas chodí s nerozpoznaným variabilním symbolem. Ten je pak pouze ve zprávě ve formátu `/vs/číslo`.
Aby to šéf financí nemusel párovat ručně, tak potřebujeme VS získávat i pro všechny slovenské platby.
> 168 api spárování sk plateb odchozí platby

- model/fio-platba.php
- model/platby.php
- tests/Model/FioPlatbaTest.php
- tests/Model/data/2021-06-10_to_2021-06-17_anonymised.json
- tests/_zavadec.php
https://trello.com/c/mF1tzIMP/855-sp%C3%A1rov%C3%A1n%C3%AD-sk-plateb
Sice jsem nasadil párování SK plateb podle VS ve zprávě, ale některé platby jsme mezitím minuli. Tahle úprava páruje a ukládá platby, které nejsou v databázi, přestože mají ID menší, než nejnovější platba.
> 855: Abychom párovali i platby, které jsme z nějakého důvodu minuli

- model/funkce/fw-database.php
- model/platby.php
- tests/Model/FioPlatbaTest.php
https://trello.com/c/mF1tzIMP/855-sp%C3%A1rov%C3%A1n%C3%AD-sk-plateb
Chyba v parametru SQL dotazu, párování Fio plateb crashovalo.
> 855: Oprava pádu při párování FIO platby

- admin/scripts/modules/finance/hromadne-odhlasovani.php
- admin/scripts/modules/finance/hromadne-odhlasovani.xtpl
- admin/scripts/modules/finance/ruseni-predmetu.xtpl
- admin/scripts/modules/uvod.php
- model/Exceptions/CanNotKickOutUserFromGamecon.php
- model/uzivatel.php
https://trello.com/c/W9Y7kpeG/873-hromadn%C3%A9-odhl%C3%A1%C5%A1en%C3%AD-%C3%BA%C4%8Dastn%C3%ADk%C5%AF-z-gc-2021
Aby Finance mohly hromadně odhlásit neplatící účastníky z Gameconu.
> 873: Finance mohou hromadně odhlašovat účastníky z Gameconu

- admin/scripts/modules/uvod.php
- admin/scripts/modules/uvod.xtpl
- model/shop-ubytovani.php
- model/shop.php
- model/uzivatel.php
https://trello.com/c/jiiChaWd/523-3-objedn%C3%A1vky-ubytov%C3%A1n%C3%AD-v-%C3%BAvod-p%C5%99ehled
Aby infopult viděl pěkně po kupě, kdo je kde ubytovaný.
> 523: Přidat do základního přehledu uživatele kde je ubytovaný

- admin/files/design/styl.css
- admin/scripts/modules/prava.php
- admin/scripts/modules/prava.xtpl
- migrace/2021-07-01_01-sloupec-posadil-k-pravum.php
- model/Cas/DateTimeCz.php
- model/uzivatel.php
https://trello.com/c/v13HEWuW/246-odhla%C5%A1ov%C3%A1n%C3%AD-neplati%C4%8D%C5%AF-2021
Už zase se řeší, kdo někoho posadil na židli. Hodím tam logování a budeme to ukazovat u židlí.
> 246: Loguj a zobrazuj kdo posadil na židli

- .gitignore
- Dockerfile
- admin/scripts/modules/ubytovani.php
- admin/scripts/modules/uvod.php
- admin/scripts/modules/uvod.xtpl
- composer.json
- composer.lock
- migrace/2021-07-01_01-potvrzeni-proti-covidu.php
- model/pomoc.php
- model/shop-ubytovani.php
- model/shop-ubytovani.xtpl
- model/shop.php
- model/uzivatel.php
- udrzba/_pomocne.php
- web/moduly/prihlaska.php
- web/sablony/blackarrow/prihlaska.xtpl
https://trello.com/c/fDNehQ71/874-mo%C5%BEnost-nahr%C3%A1t-potvrzen%C3%AD-o-testu-do-p%C5%99ihl%C3%A1%C5%A1ky
Jelikož brebera otravuje, tak musíme být na stráži a vyžadovat od účastníků potvrzení, že jsou cajk. Tohle není finální verze, ale nějak se to semlelo, že aspoň to nahrávání potvrzení z přihlášky musíme nasadit.
> 874 možnost nahrát potvrzení o testu do přihlášky

- admin/index.php
- admin/scripts/modules/muj-prehled.php
- model/uzivatel.php
- web/index.php
https://trello.com/c/LWhIUUuD/860-p%C5%99ihl%C3%A1%C5%A1en%C3%AD-z-webu-neplat%C3%AD-pro-admin
Aby odkaz na admin z webu směřoval rovnou na Moje aktivity
> 860: Odkaz na admin z webu míří na Moje aktivity, pokud to má smysl

- admin/scripts/zvlastni/reporty/zazemi-a-program-seznam-ucastniku-a-tricek-grouped.php
- model/Zidle.php
- model/uzivatel.php
https://trello.com/c/Oj3RN88d/851-roz%C5%A1%C3%AD%C5%99it-report-seznam-%C3%BA%C4%8Dastn%C3%ADk%C5%AF-a-tri%C4%8Dek-grouped-pro-bal%C3%AD%C4%8Dkov%C3%A1n%C3%AD
Všechny možné položky z eshopu do reportu
> 851: Report s účastníky rozšířen o další položky eshopu

- model/uzivatel.php
https://trello.com/c/Oj3RN88d/851-roz%C5%A1%C3%AD%C5%99it-report-seznam-%C3%BA%C4%8Dastn%C3%ADk%C5%AF-a-tri%C4%8Dek-grouped-pro-bal%C3%AD%C4%8Dkov%C3%A1n%C3%AD#comment-60ec18f22f9b6551d5ae4f91
Zapomněl jsem tam hack který u každého uživatele ukazoval všechny role
> 851: Ostraněn zapomenutý testovací kód který u každého ukazoval všechny role

- admin/scripts/modules/uvod.php
- model/Cas/DateTimeCz.php
- model/uzivatel-covid-potvrzeni.xtpl
- model/uzivatel.php
- web/moduly/prihlaska/bez-stranky/potvrzeni-proti-covidu.php
- web/moduly/prihlaska/prihlaska.php
- web/soubory/blackarrow/_spolecne/hinted.less
- web/tridy/modul.php
https://trello.com/c/fDNehQ71/874-mo%C5%BEnost-nahr%C3%A1t-potvrzen%C3%AD-o-testu-do-p%C5%99ihl%C3%A1%C5%A1ky
Aby bylo návštěvníkovi z přihlášky jasnější, že už své potvrzení proti Covidu nahrál.
> 874 možnost nahrát potvrzení o testu do přihlášky nahráno

- admin/scripts/zvlastni/reporty/zazemi-a-program-seznam-ucastniku-a-tricek-grouped.php
- model/uzivatel.php
https://trello.com/c/Oj3RN88d/851-roz%C5%A1%C3%AD%C5%99it-report-seznam-%C3%BA%C4%8Dastn%C3%ADk%C5%AF-a-tri%C4%8Dek-grouped-pro-bal%C3%AD%C4%8Dkov%C3%A1n%C3%AD
Přidáváme rok k názvu kostky do reportu pro inforpult.
> Ukazovat rok u kostek v reportu s přehledem předmětů

- admin/scripts/zvlastni/reporty/stravenky-bianco.php
- admin/scripts/zvlastni/reporty/stravenky-bianco.xtpl
- admin/scripts/zvlastni/reporty/stravenky.php
- migrace/2021-07-15-samostatny-skript-pro-stravenky-bianco.php
Nějak se nám rozbila stránka s malými stravenkami pro tisk. A když už jsme v tom opravování, tak to rovnou trochu pročistíme.
> Opraveno zobrazeni malych stravenek bez jmena uzivatele

- admin/scripts/zvlastni/last-minute-tabule.php
- admin/scripts/zvlastni/last-minute-tabule.xtpl
- model/aktivita.php
Aby se na https://admin.gamecon.cz/last-minute-tabule zobrazoval čas první nadcházející aktivity a ne poslední.
> Oprava zobrazeneho casu nadchazejicich volnych aktivit

- model/lokace.php
- model/program.php
- web/soubory/blackarrow/program/program-trida.css
Aby se v programu https://gamecon.cz/program/nedele zobrazovala také místnost aktivity
> Pridat mistnost a dvere na kalendar aktivit

- admin/scripts/zvlastni/program-mistnosti.php
- model/program.php
Skryjeme místnost s aktivitou pro běžné návštěvníky, aby nám nelezli rovnou do místností, ale chodili správně na sraziště.
> zobrazovat místnosti v programu jen organizátorům a infopultu

- admin/scripts/modules/prezence/prezence.php
- admin/scripts/modules/prezence/prezence.xtpl
- admin/scripts/modules/uvod.xtpl
- model/aktivita-prezence.php
- model/aktivita.php
- model/pomoc-texty.php
- model/pomoc.php
- model/pomoc.xtpl
- web/sablony/blackarrow/prihlaska.xtpl
https://trello.com/c/Br7L3lHX/849-%C3%BAprava-text%C5%AF-v-p%C5%99ihl%C3%A1%C5%A1ce
Krapet jsme minuli zastaralé texty v přihlášce. Upravujeme.
> 849: Pozdě ale přeci - upraveny texty v přihlášce

- readme.md
> update readme - default innoDB

- admin/files/design/styl.css
- admin/scripts/modules/finance/finance.php
- admin/scripts/modules/finance/finance.xtpl
- admin/scripts/modules/uvod.php
- admin/scripts/modules/uvod.xtpl
- admin/scripts/zvlastni/reporty/sdilene-hlavicky.php
- model/chyba.php
- model/finance.php
- model/funkce/web-funkce.php
https://trello.com/c/3XYMfkDL/887-finance-a-registrace-lid%C3%AD-po-gc
Aby se stav financí ukazoval i nepřihlášenému na GC a šlo mu připsat platbu.
> 887: Stav financí se ukazuje i nepřihlášenému na GC a lze mu připsat platbu.

- admin/files/design/styl.css
- admin/files/omnibox.js
- admin/files/prezence.js
- admin/scripts/modules/prezence/prezence.php
- admin/scripts/modules/prezence/prezence.xtpl
- admin/scripts/zvlastni/ajax-omnibox.php
- admin/scripts/zvlastni/program-uzivatele.php
- migrace/2021-07-21-lepsi-popis-pro-admin-zidli.php
- model/Pravo.php
- model/finance.php
- model/uzivatel.php
- nastaveni/nastaveni.php
Kdo má právo na změnu historie aktivit, ten může přidávat účastníky na uzavřenou aktivitu.
> Moznost editovat prezenci po uzavreni

- migrace/072.php
- web/moduly/program.php
- web/soubory/blackarrow/program/program.less
uprava barevne legendy na hardcode html+style
> 839: Refactoring hacku legendy

- admin/scripts/modules/uvod.php
- admin/scripts/modules/uvod.xtpl
- migrace/2021-11-20-pridat-unikatni-index-na-fio-id.php
- model/finance.php
- model/fio-platba.php
- model/funkce/fw-database.php
https://trello.com/c/zsb8bCet/884-nepropsan%C3%A1-platba-do-adminu
Občas se stane, že se platba z Fio nedostane automatem do Gameconu a pak se musí zadat ručně. Pak ale hrozí, že automat tu samou přidá zpětně. Klíčem je Fio ID, tedy ID transakce - když přidáme ruční transakci i s ním, tak ji automat správně přeskočí.
**edit**: Finance tuhle funkci odmítly, nechávám ji jen pro "superadminy", což je pevný seznam ajťáků Gameconu
> 884: K ručně zadané platbě lze přidat Fio ID

- admin/scripts/modules/statistiky.php
Započítávat do statistik prodejů i kostky s rozšířeným názvem
> Preklopeni rocniku na 2022

- admin/scripts/modules/aktivity/_Import/AktivitaSqlSloupce.php
- admin/scripts/modules/aktivity/_Import/ImportValuesSanitizer.php
- admin/scripts/modules/aktivity/novy-org.php
- admin/scripts/modules/finance/finance.php
- admin/scripts/modules/statistiky.php
- admin/scripts/modules/uvod.php
- admin/scripts/zvlastni/reporty/aktivity.php
- admin/scripts/zvlastni/reporty/celkovy-report.php
- admin/scripts/zvlastni/reporty/maily-neprihlaseni.php
- admin/scripts/zvlastni/reporty/maily-prihlaseni.php
- admin/scripts/zvlastni/reporty/maily-vypraveci.php
- admin/scripts/zvlastni/reporty/neprihlaseni-vypraveci.php
- admin/scripts/zvlastni/reporty/parovani-ankety.php
- admin/scripts/zvlastni/reporty/stravenky.php
- admin/scripts/zvlastni/reporty/ubytovani.php
- admin/scripts/zvlastni/reporty/update-zustatku.php
- admin/scripts/zvlastni/reporty/zazemi-a-program-pocet-sledujicich-pro-aktualni-rok.php
- migrace/2021-12-17-prejmenovat-slevu-na-bonus.php
- model/Pravo.php
- model/Zidle.php
- model/aktivita.php
- model/finance.php
- model/program.php
- model/uzivatel.php
- nastaveni/nastaveni.php
- tests/Db/UzivatelDbTest.php
- web/moduly/prihlaska/prihlaska.php
https://trello.com/c/SqAhSi8t/870-oprava-kontrola-report%C5%AF-v-adminu
Některé počty účastníků neseděli kvůli dvakrát započítaným náhradníkům.
A suma bonusu za vedení aktivit taky kecala, protože někteří vypravěči ji prostě nemají dostat.
> 870: Opraveny počty účastníků a bonus za vedení aktivit v reportu historie aktivit

- admin/scripts/modules/uvod.php
Přidal jsem také vypsanou general Exception, kdyby náhodou něco takového vzniklo, ať to z toho může člověk zkusit vyčíst, než třeba předá jako chybu.
Trello https://trello.com/c/APqpLH6u/534-chybov%C3%A1-hl%C3%A1%C5%A1ka-u-zm%C4%9Bny-emailu
> Try catch ifs

- web/moduly/program.php
> Ahoj, takový mini bug který asi ani není nějak extra důležitý. Program teď spamuje refresh protože timeout přesahuje int32, tak kdyby tam šlo dát cap ať to nepřeteče. Pak mi tu pořád refreshuje na pozadí zapnutej program :)
https://github.com/gamecon-cz/gamecon/blob/master/web/moduly/program.php#L138
> Program je refreshnut jen když je začátek v blízké budoucnosti

- admin/scripts/modules/aktivity/prihlaseni-drd.php
Jestli jsem to dobře pochopil z kódu, tak PJ je vedený jako organizátor u dané Aktivity (která je v tomto případě tým), že? Případně změním, ale takhle jsem to vypozoroval a nemám to moc jak otestovat.
> Mdrd mass emails

- admin/scripts/zvlastni/reporty/zazemi-a-program-prehled-mistnosti.php
Změna reportu Zázemí & Program: Přehled místností tak, aby odpovídal importnímu souboru místností.
https://trello.com/c/YS7BnqDs/917-report-m%C3%ADstnost%C3%AD
> Změna reportu Zázemí & Program: Přehled místností

- nastaveni/nastaveni.php
> fix konstanty P_ORG_AKCI vs P_ORG_AKTIVIT

- admin/scripts/zvlastni/reporty/finance-lide-v-databazi-a-zustatky.php
Na žádost Pavla jsem upravila report Finance: Lidé v databázi + zůstatky - přidání emailu a tel. čísla, aby Pavel mohl kontaktovat lidi ohledně promlčování zůstatků, viz https://trello.com/c/aK6Q9HCo/920-%C3%BAprava-proml%C4%8Den%C3%AD-z%C5%AFstatk%C5%AF
> Uprava reportu finance lide v databazi a zustatky

- admin/scripts/modules/uvod.php
- admin/scripts/modules/uvod.xtpl
- model/shop-jidlo.xtpl
- model/shop.php
- nastaveni/nastaveni.php
- web/moduly/prihlaska/prihlaska.php
- web/sablony/blackarrow/prihlaska.xtpl
Viz [trello](https://trello.com/c/ehzwLfEc/543-%C3%BApravy-p%C5%99ihl%C3%A1%C5%A1ky-mastercard)
> Registration changes

- migrace/2022-05-05_03-kurz-euro-do-systemoveho-nastaveni.php
- migrace/2022-05-09_01-poradi-a-skupina-do-systemoveho-nastaveni.php
- migrace/2022-05-09_02-bonusy-vypravecu-do-systemoveho-nastaveni.php
- model/SystemoveNastaveni/SystemoveNastaveni.php
- model/finance.php
- nastaveni/nastaveni.php
- nastaveni/virtualni-nastaveni-pro-ide.php
https://trello.com/c/jtDu0OoQ/926-zm%C4%9Bny-bonus%C5%AF
Aby admini mohli sami měnit bonusy vypravěčů za pořádání aktivit podle jejich délky.
> 926: Slevy vypravěčů za aktivity do systémového nastavení

- migrace/2022-05-11_01-shop-upravy.php
- model/Cas/DateTimeGamecon.php
- model/cenik.php
- model/shop-vstupne.xtpl
- web/soubory/blackarrow/shop/shop-vstupne.less
https://trello.com/c/ehzwLfEc/543-%C3%BApravy-p%C5%99ihl%C3%A1%C5%A1ky-mastercard
> Oprava shopu 2022

- migrace/2022-05-12-zvednout-cenu-kostek-na-25.php
https://trello.com/c/ehzwLfEc/543-%C3%BApravy-p%C5%99ihl%C3%A1%C5%A1ky-mastercard
Inflace je tady.
Zvedáme cenu všech kostek na 25.-
> 543: Cena kostek zvednuta na 25

- model/nahled.php
- web/moduly/prihlaska/prihlaska.php
- web/sablony/blackarrow/prihlaska.xtpl
https://trello.com/c/mIhJS10k/923-nahr%C3%A1t-e-shop#comment-627e8929f5b82c7f6db1291a
Obrázky tašky, kostky Cthulhu, tílka a bloku pro eshop
> 923 nahrát e shop skryt chybejici predmety ale nechat v html

- migrace/2022-05-14_01-shop-3XL-trička.php
- migrace/pomocne/db-migrations/src/DbMigrations.php
- migrace/pomocne/db-migrations/src/Migration.php
- model/shop.php
https://trello.com/c/mIhJS10k/923-nahr%C3%A1t-e-shop#comment-627f78c5d9a4c259ba6ffef6
Skutečná trička pro opravdové chlapí!
> 923: Přidána XXXL trička pro 2022

- migrace/2022-05-17_1-Warhammer_40k_turnaj_1_kolo-otevren.php
- model/aktivita.php
https://trello.com/c/5nrEXKJO/933-hacknout-1-p%C5%99ihl%C3%A1%C5%A1en%C3%A9ho-a-t%C3%BDm-na-wg-turnaji
> 933: Warhammer 40k turnaj - 1.kolo je připravené jako teamová ale už se založeným týmem

- migrace/2022-05-18_01-import-mistnosti-2022-v3.php
https://trello.com/c/KdsmDsdq/937-import-m%C3%ADstnost%C3%AD#comment-6284041e0a3f63872d010e12
Že by místnosti 2022 naposledy?
> 937: Ještě jedna verze místností

- model/shop-jidlo.xtpl
- model/shop.php
- nastaveni/nastaveni.php
https://trello.com/c/B7f4FpmL/943-zastavit-prodej-j%C3%ADdla-a-zv%C3%BD%C5%A1it-cenu-pro-budouc%C3%AD-objedn%C3%A1vky
Když se daří tak se daří, aneb dodavatel nám s křížkem po funuse zdražil jídlo o dvacku.
> 943: Prodej jídla dočasně zastaven

- model/shop-jidlo.xtpl
https://trello.com/c/B7f4FpmL/943-zastavit-prodej-j%C3%ADdla-a-zv%C3%BD%C5%A1it-cenu-pro-budouc%C3%AD-objedn%C3%A1vky
Přidáno vysvětlení, proč nelze objednávat jídlo
> 943 zastavit prodej jídla a zvýšit cenu pro budoucí objednávky

- admin/cron.php
Řeší problém s nefunkčností cronu na lokále.
> Fix: Nesnaž se kontaktovat FIO API, pokud není nastaven správný token

- web/moduly/aktivity.php
- web/sablony/blackarrow/aktivity.xtpl
- web/soubory/blackarrow/aktivity/aktivity.less
https://trello.com/c/2i4uKpvW/817-sekce-n%C3%A1zev-aktivity-m%C3%A1-max-2-%C5%99%C3%A1dky
Aby se v programu ukazoval celý název i když je fakt dlouhý
> 817: Názvy aktivit v jednotlivých sekcích mají velikost fontu relativní podle obrazovky

- model/aktivita.php
- model/funkce/fw-database.php
- model/uzivatel.php
- nastaveni/nastaveni.php
https://trello.com/c/FqMlsXGw/942-reagovat-na-zm%C4%9Bny-pr%C3%A1v-hned
Aby se změny v profilu a právech uživatele projevily hned a ne až po odhlášení a přihlášení.
> 942: Reagovat na změny práv hned

- admin/scripts/modules/finance/slucovani.php
- admin/scripts/modules/finance/slucovani.xtpl
https://trello.com/c/2HRqSR2p/558-bug-slu%C4%8Dov%C3%A1n%C3%AD-u%C5%BEivatel%C5%AF
Aby to nepadalo na chybu, ale hlásilo co je špatně, když jeden z uživatelů ke sloučení neexistuje.
> 932: Neexistující ID uživatele ke slučení hodí hlášku

- admin/index.php
- migrace/2022-05-22_01-zidle-neodhlasovat.php
- migrace/2022-05-29_01-zidle-herman.php
- model/Pravo.php
- model/Zidle.php
- model/uzivatel.php
- nastaveni/nastaveni.php
https://trello.com/c/zSyFHsFc/875-dal%C5%A1%C3%AD-%C5%BEidle-role
Nová role Herman a v adminu zobrazená existující role Dobrovolník senior.
> 875: Přidána židle Herman a titul v adminu pro Dobrovolník senior

- migrace/2022-05-29_01-url-uzivatele.php
- model/funkce/fw-general.php
- model/uzivatel.php
- web/moduly/aktivity.php
https://trello.com/c/RkBBO7G8/845-medailonky-nefunguj%C3%AD-p%C5%99i-nestandardn%C3%AD-p%C5%99ezd%C3%ADvce
Aby každý uživatel měl URL se svým profilem.
> 845: Uživatelé mají předdefinovaná URL se svým profilem

- admin/files/design/styl.css
- model/editor-aktivity.xtpl
https://trello.com/c/NKJiBLDm/907-p%C5%99idat-n%C3%A1pov%C4%9Bdu-k-nahr%C3%A1v%C3%A1n%C3%AD-obr%C3%A1zku-k-aktivit%C4%9B
Aby se vědělo, jaká kvalita a rozměry obrázku potřebujeme u aktivit
> 907: Přidány labely a tooltip pro obrázek aktivity

- .github/workflows/run-tests.yml
> 562: Přidány testy pro novou verzi

- migrace/2022-05-17_1-Warhammer_40k_turnaj_1_kolo-otevren.php
- migrace/2022-06-08_1-Oldest_Old_World-Tournament-1-kolo.php
- model/funkce/fw-general.php
- tests/funkce/FunkceTest.php
https://trello.com/c/5nrEXKJO/933-hacknout-1-p%C5%99ihl%C3%A1%C5%A1en%C3%A9ho-a-t%C3%BDm-na-wg-turnaji
Hacknutí prvního přihlášeného na turnaj _Oldest Old World Tournament - WFB 6.5 edition_.
> 933: Hack otevření týmu pro Oldest Old World Tournament - WFB 6.5 edition

- migrace/2022-06-22_01-shop-dalsi-xxl-tricka.php
https://trello.com/c/Pk9mGALh/959-%C3%BApravy-v-e-shopu-2022-2
Tričko červené pánské XXXL
Tílko modré dámské XXL
Tílko červené dámské XXL
Tílko účastnické dámské XXL
> 959: Další XXL trička 2022

- docker-compose.dev.yml
- nastaveni/verejne-nastaveni-beta.php
- nastaveni/verejne-nastaveni-produkce.php
- nastaveni/zavadec-zaklad.php
- udrzba/_pomocne.php
Abychom snáze mohli měnit některá nastavení na betě a v produkci a nepřepisovali si navzájem obsah souborů tak tajných, že nikdo neví co v nich má ten druhý.
> Některá nastavení jsou veřejná a verzována

- web/soubory/blackarrow/program/program.less
Namísto "odsledovat" použijeme "zrušit sledování"
> Upravit název tlačítka na zrušení sledování aktivity

- web/soubory/blackarrow/program/program-trida.css
https://trello.com/c/3jX06vw9/897-color-coding-programu-v-adminu
> Admin program color fix

- admin/scripts/modules/_ubytovani-a-dalsi-obcasne-infopultakoviny-import-ubytovani.php
- admin/scripts/zvlastni/reporty/finance-report-ubytovani.php
- model/shop-ubytovani.php
- model/uzivatel.php
https://trello.com/c/JelzTonf/900-import%C3%A9r-bal%C3%AD%C4%8Dk%C5%AF-a-ubytov%C3%A1n%C3%AD
Abychom mohli importovat s kým chce být kdo ubytován
> 900: Možnost importovat s kým chce být jedinec ubytován

- admin/files/design/online-prezence.css
- admin/files/online-prezence/online-prezence.js
- model/Aktivita/OnlinePrezence/OnlinePrezenceHtml.php
- model/Aktivita/OnlinePrezence/templates/online-prezence.xtpl
https://trello.com/c/zPM7Eh56/240-e-prezen%C4%8Dky-feedback-pro-cemi#comment-62c94a4688585d2736baf28d
Aby online prezence zobrazovala počet přihlášených
> 240 e prezenčky feedback pro cemi

- migrace/2022-07-09_01-uzavrit-nabidku-ubytovani-2022-11-7.php
- model/shop-ubytovani.php
- model/shop-ubytovani.xtpl
- model/uzivatel.php
- nastaveni/nastaveni.php
- web/moduly/prihlaska/prihlaska.php
- web/sablony/blackarrow/prihlaska.xtpl
- web/sablony/prihlaska.xtpl
https://trello.com/c/Jc0yVarC/974-zm%C4%9Bna-uzav%C3%ADrky-ubytov%C3%A1n%C3%AD
> 974: Úprava datumů pro objednání ubytování a placení

- model/Shop/templates/shop-ubytovani.xtpl
https://trello.com/c/Jc0yVarC/974-zm%C4%9Bna-uzav%C3%ADrky-ubytov%C3%A1n%C3%AD
3) U ubytování zobrazit poznámku (podobně jako u triček), "Možnost objednávek ubytování přes web už skončila. Zbylé postele lze zarezervovat přes e-mail info@gamecon.cz."
> 974: Přidán mailový kontakt na Gamecon jako poslední možnost získat ubytování

- admin/scripts/zvlastni/reporty/celkovy-report.php
- model/funkce/fw-general.php
- model/report.php
Během práce na https://trello.com/c/FpeCZBWI/848-redesign-%C3%BAvodn%C3%AD-str%C3%A1nky-v-adminu jsem jen tak mimochodem narazil na to, že v BFGR reportu tak nějak chybí lidé, co si něco objednali, nebo poslali peníze, ale nejsou přihlášeni na GC.
Opravujeme.
> 848: Vypsat v BFGR reportu každého s platbou nebo objednavkou ať už je přihlášen nebo ne

- admin/scripts/zvlastni/reporty/celkovy-report.php
https://trello.com/c/LLI0KtQq/979-oprava-bfgr-nep%C5%99ihl%C3%A1%C5%A1en%C3%BDch-%C3%BA%C4%8Dastn%C3%ADk%C5%AF#comment-62d406364be66a5672c6e19b
Neseděl počet sloupců v datech a v hlavičce - v hlavičce jsme zapomněli na _Odjel_
> 979: Přidána zapomentuá hlavička v BFGR kdy odjel

- admin/scripts/modules/infopult.xtpl
- model/Shop/Shop.php
https://trello.com/c/9Tf62Bxj/981-%C3%BApravy-v-e-shopu-2022-%C4%8D%C3%A1st-pades%C3%A1t%C3%A1#comment-62d45291063f9e0f64e3a4e6
Aby šlo vynulovat dobrovolné vstupné.
> 981 úpravy v e shopu 2022 část padesátá

- admin/files/design/styl.css
- admin/scripts/modules/_infopult_ovladac.php
- admin/scripts/modules/infopult.php
- admin/scripts/modules/infopult.xtpl
- model/Shop/Shop.php
- model/Uzivatel/Finance.php
- model/uzivatel.php
https://trello.com/c/U3v8sMzZ/300-zm%C4%9Bny-v-adminu-2022
Aby ten kdo má židli Finance mohl rušit objednávky předmětů
> 300: Možnost mazat objednávky z adminu

- admin/scripts/modules/aktivity/prihlaseni-drd.php
- admin/scripts/modules/aktivity/prihlaseni-drd.xtpl
- migrace/2022-07-22_01-log-udalosti.php
- model/Logger/LogUdalosti.php
https://trello.com/c/0tUeAPAy/985-mdrd-email-postupiv%C5%A1%C3%ADm
> 985: Možnost odeslat email o postupu v mDrD

- migrace/2022-07-28_01-nastaveni-do-kdy-lze-pridavat-ucastniky.php
- model/Aktivita/Aktivita.php
- model/Aktivita/OnlinePrezence/OnlinePrezenceAjax.php
- model/Aktivita/OnlinePrezence/OnlinePrezenceHtml.php
- model/Aktivita/OnlinePrezence/templates/online-prezence-ucastnik.xtpl
- model/Aktivita/OnlinePrezence/templates/online-prezence.xtpl
- model/SystemoveNastaveni/SystemoveNastaveni.php
Admin co není vypravěč už nemůže přidávat do ukončené aktivity.
Vypravěč může do neuzavřené aktivity přidávat ještě několik dní po GC.
> 576 plná elektronizace prezenček

- admin/scripts/modules/infopult.php
- model/Uzivatel/Finance.php
Občas potřebujeme účastníkům smazat "nákup" dobrovolného vstupného.
Teď už na to bude nástroj.
> 300: Z admin infpultu lze smazat dobrovolné vstupné

- .docker/Dockerfile
- .docker/gamecon-run.sh
- .github/workflows/run-tests.yml
- Dockerfile
- admin/scripts/zvlastni/last-minute-tabule.php
- admin/scripts/zvlastni/reporty/celkovy-report.php
- composer.json
- composer.lock
- docker-compose.dev.yml
- model/Aktivita/Aktivita.php
- model/Cas/DateTimeCz.php
- model/Statistiky/Statistiky.php
- model/SystemoveNastaveni/SystemoveNastaveni.php
- model/e-p-d-o.php
- model/funkce/fw-general.php
- model/obrazek.php
- model/uzivatel.php
- tests/Db/Dataset.php
- tests/funkce/FunkceTest.php
https://trello.com/c/P6ibwrP7/562-p%C5%99%C3%ADprava-na-php-81
Drobné změny nutné pro běh na PHP 8.1
⚠️ Pozor, po této úpravě **poběží Gamecon jenom na PHP 8.1+**
> 562 příprava na php 8.1

- admin/scripts/zvlastni/reporty/bfgr-report.php
- model/Uzivatel/Finance.php
https://trello.com/c/LLI0KtQq/979-oprava-bfgr-nep%C5%99ihl%C3%A1%C5%A1en%C3%BDch-%C3%BA%C4%8Dastn%C3%ADk%C5%AF
>  Přidat sloupec "Brigádnické odměny" za sloupec "Proplacený bonus za vedení aktivit" (závislé na https://trello.com/c/TYqQgYan/525-3-mo%C5%BEnost-p%C5%99ipsat-pen%C3%ADze-na-gc-%C3%BA%C4%8Det-p%C5%99es-aktivitu)
> 979: Přidána suma brigádnické odměny do BFGR

- admin/index.php
- composer.json
- composer.lock
- model/Vyjimkovac/VyjimkovacChyba.php
- model/XTemplate/XTemplate.php
- nastaveni/nastaveni-local-default.php
- nastaveni/nastaveni.php
- patches/tracy-tracy-src-tracy-helpers-php.patch
- tests/Db/UzivatelDbTest.php
- tests/Model/FioPlatbaTest.php
- tests/Model/SystemoveNastaveni/SystemoveNastaveniTest.php
- tests/funkce/FunkceTest.php
- tests/web/StrankyWebuTest.php
Abychom věděli z testů aspoň to, že padly homepages adminu či webu.
> Testy stranek

- model/uzivatel.php
- přidal jsem možnost mít 'plusko' v mailu (já osobně u gmailu občas využívám)
- napsal jsem funkci (regexem by to byl pain) na validaci data
viz https://trello.com/c/wlm2ZoPW/521-duplicitn%C3%AD-login-e-mail-apod
> Registrace duplicitni login mail

- .docker/Dockerfile
- .github/workflows/run-tests.yml
- admin/index.php
- admin/scripts/modules/aktivity/_Import/ImportSqlMappedValuesChecker.php
- admin/scripts/modules/statistiky.php
- admin/scripts/prihlaseni.php
- admin/templates/zakazano.xtpl
- docker-compose.dev.yml
- migrace/054.php
- migrace/055.php
- migrace/2022-02-23-povolit-mazani-z-tabulky-instanci.php
- model/Pravo.php
- model/Shop/Shop.php
- model/Statistiky/Statistiky.php
- model/funkce/fw-database.php
- model/funkce/fw-general.php
- model/uzivatel.php
- nastaveni/verejne-nastaveni-tests.php
- nastaveni/zavadec-zaklad.php
- tests/Aktivity/AktivitaTagyTest.php
- tests/Aktivity/AktivitaTymovePrihlasovaniTest.php
- tests/Aktivity/UzivatelMaVolnoTest.php
- tests/Db/DbTest.php
- tests/Model/SystemoveNastaveni/SystemoveNastaveniTest.php
- tests/_zavadec.php
- tests/web/AbstractWebTest.php
- tests/web/StrankyWebuTest.php
Další rozšíření automatických testů.
Detekce obsazeného portu lokálního web serveru.
Úprava deploye, aby během něj neběžely testy zbytečně ještě samostatně, když si je pouští sám.
> Admin web testy

- model/program.php
- ui/src/pages/program/program.less
- web/soubory/blackarrow/program/program-trida.css
- web/soubory/blackarrow/program/program.less
2 řádky na desktopu (na mobilu beze změny)
> Zalamování řádků v programu

- admin/scripts/modules/aktivity/medailonky.php
- migrace/2022-11-30_01-foreign-keys-kaskady.php
- migrace/pomocne/db-migrations/src/Migration.php
- model/medailonek.php
Přidány cizí klíče kde chyběly
> Přidány cizí klíče a sjednoceny názvy cizích klíčů

- model/SystemoveNastaveni/AnonymizovanaDatabaze.php
Mírná zlepšení v mezích zákona
> 1035: admin v anonymizované databázi

- model/SystemoveNastaveni/AnonymizovanaDatabaze.php
> admin v anonymizované databázi

- model/SystemoveNastaveni/AnonymizovanaDatabaze.php
Oprava admin uživatele pro anonymní databázi
> 1035: Oprava admin uživatele pro anonymní databázi

- admin/files/online-prezence/online-prezence-potvrzovaci-modal.js
- model/Aktivita/OnlinePrezence/OnlinePrezenceHtml.php
- model/Aktivita/OnlinePrezence/templates/online-prezence.xtpl
Oprava detekce zaškrtnutého účastníka.
Návrh na jiné názvy funkcí.
> Opravena detekce potvrzené účasti v online prezence modalu

- ui/src/pages/obchod/components/Obchod/Obchod.tsx
- web/moduly/prihlaseni.php
- web/moduly/registrace.php
- web/soubory/blackarrow/_spolecne/_zaklad.less
- web/soubory/blackarrow/formular/formular.less
Zdaleka to není ideální, ale je to výrazně lepší (není to rozbité na většině zařížení :D)
> 828 přihláška na mobilu má rozbitý layout v desktop zobrazení

- admin/scripts/zvlastni/reporty/report-infopult-ucastnici-balicky.php
- admin/scripts/zvlastni/reporty/report-infopult-ucastnici-balicky.xtpl
- model/report.php
Trello 994: https://trello.com/c/IYRkvOpJ
> Balickovy report je "print-friendly" a trideny podle poctu typu predmetu

- nastaveni/nastaveni.php
https://trello.com/c/I3bAyhX9/1004-p%C5%99eklopit-ro%C4%8Dn%C3%ADk-uzav%C5%99en%C3%AD-ro%C4%8Dn%C3%ADku
2023
> 2023: Změna ročníku na 2023

- admin/scripts/modules/prava.php
- admin/scripts/prihlaseni.php
Detail židle v adminu se nezobrazoval, protože kód chybně četl ID židle z requestu
> Fix detailu zidle

- admin/cron.php
- admin/cron/.htaccess
- admin/cron/cron_zavadec.php
- admin/cron/zaloha_databaze.php
- composer.json
- composer.lock
- model/SystemoveNastaveni/AnonymizovanaDatabaze.php
- model/SystemoveNastaveni/KopieOstreDatabaze.php
- model/SystemoveNastaveni/NastrojeDatabaze.php
- model/SystemoveNastaveni/SystemoveNastaveni.php
- model/SystemoveNastaveni/SystemoveNastaveniHtml.php
- model/Vyjimkovac/VyjimkovacChyba.php
- patches/dg-mysql-dump-src-mysqlimport-php.patch
- tests/Model/SystemoveNastaveni/SystemoveNastaveniTest.php
https://trello.com/c/7HBza29K/1042-nahradit-mysql-dump
> 1042: Nahrazena knihovna na zálohy a kopírování databáze

- admin/scripts/zvlastni/reporty/finance-report-neplaticu.php
- migrace/2023-02-06_01-sjednotit-nazvy-konstant-s-hromadnym-odhlasovanim.php
- migrace/2023-02-06_02-cas-tretiho-hromadneho-odhlasovani.php
- model/Cas/DateTimeGamecon.php
- model/Cas/DateTimeImmutableStrict.php
- model/Cas/Exceptions/InvalidModifyFormat.php
- model/SystemoveNastaveni/SystemoveNastaveni.php
- model/Uzivatel/KategorieNeplatice.php
- nastaveni/nastaveni.php
- tests/Model/Cas/DateTimeGameconTest.php
- tests/Model/SystemoveNastaveni/SystemoveNastaveniTest.php
- web/moduly/finance.php
- web/moduly/prihlaska/prihlaska.php
https://trello.com/c/kqoArJje/1040-p%C5%99idat-3-vlnu-odhla%C5%A1ov%C3%A1n%C3%AD-neplati%C4%8D%C5%AF
> 1040 přidat 3 vlnu odhlašování neplatičů

- admin/scripts/modules/aktivity/upravy.php
- model/Aktivita/templates/editor-aktivity.xtpl
https://trello.com/c/v6nLdVYs/1048-bez-slev-je-za%C5%A1krtnut%C3%A9-a-neodstraniteln%C3%A9
> 1048 bez slev je zaškrtnuté a neodstranitelné

- admin/scripts/modules/aktivity/aktivity.php
https://trello.com/c/YvLjmH53/1046-chyb%C3%AD-tla%C4%8D%C3%ADtko-pro-publikaci-aktivaci-aktivit
> 1046: Fix porovnávaných stavů aktivit po nedávné změně

- .github/workflows/deploy-jakublounek.yml
- nastaveni/verejne-nastaveni-beta.php
- nastaveni/verejne-nastaveni-jakublounek.php
Aby to Kubovi běhalo i po upgrade systémů na serveru
> Update nastavení pro jakublounek podle poslední módy

- web/moduly/titulka.php
- web/sablony/blackarrow/titulka.xtpl
- web/soubory/blackarrow/sponzori/sponzori.less
https://trello.com/c/qHTa9cN5/880-zv%C4%9Bt%C5%A1en%C3%AD-log-sponzor%C5%AF-na-webu
> 880 zvětšení log sponzorů na webu

- composer.lock
- model/Report/BfgrReport.php
- model/SystemoveNastaveni/SystemoveNastaveni.php
- model/SystemoveNastaveni/SystemoveNastaveniHtml.php
- model/Uzivatel/Finance.php
- nastaveni/db-migrace.php
- tests/_zavadec.php
Něco málo změn původně z jiné branche
> Kategorie predmetu

- model/uzivatel.php
Creation of dynamic property Uzivatel::$medailonek is deprecated
> Vyřešen deprecated kvůli dynanicky vytvářené property

- admin/scripts/modules/aktivity/_Import/ImportSqlMappedValuesChecker.php
- admin/scripts/modules/aktivity/_Import/ImportStepResult.php
- admin/scripts/modules/aktivity/_import.php
- admin/scripts/modules/aktivity/upravy.php
- model/Aktivita/Aktivita.php
- model/Web/Urls.php
- model/chyba.php
- model/funkce/web-funkce.php
https://trello.com/c/4IGOeCIx/1009-hodit-hl%C3%A1%C5%A1ku-warning-%C5%BEe-aktivita-je-v-obsazen%C3%A9-m%C3%ADstnosti
> 1009: Přidání aktivity do místnosti, kde už je jiná aktivita, hodí varování

- admin/scripts/modules/finance/shop.php
https://trello.com/c/aT2jScjy/1060-nefunguje-nastaven%C3%AD-eshopu
Na ostrou nám protekla změna, která tam být ještě něměla.
> Fix crash v admin Financích

- model/Aktivita/Aktivita.php
- model/Aktivita/templates/editor-aktivity.xtpl
Nastavit, aby brigádnickou aktivitu admin nabízel systém na konci drop-down menu? To samé by asi bylo užitečné pro technické. (Nice to have)
https://trello.com/c/TYqQgYan/525-3-mo%C5%BEnost-p%C5%99ipsat-pen%C3%ADze-na-gc-%C3%BA%C4%8Det-p%C5%99es-aktivitu
> Typ aktivity Technická a Brigádnická až na konec v adminu

- .github/workflows/cron-schedule.yml
- admin/cron.php
Github actions dovolí pouštět jednou za pět minut něco-jako-cron z nastavení v hlavní větvi, takže master.
> Spouštění CRONu přes Github actions

- admin/scripts/modules/aktivity/_Import/ImportSqlMappedValuesChecker.php
- model/Aktivita/TypAktivity.php
https://trello.com/c/4IGOeCIx/1009-hodit-hl%C3%A1%C5%A1ku-warning-%C5%BEe-aktivita-je-v-obsazen%C3%A9-m%C3%ADstnosti
> Fix varování o obsazené místnosti, aby to počítalo všechny předchozí aktivity kterým sdílení místnosti vadí

- admin/scripts/modules/aktivity/_Import/ImportSqlMappedValuesChecker.php
- model/Aktivita/Aktivita.php
https://trello.com/c/6KesyssC/1054-import-místností-2023
Chybně jsem seskládal SQL parametry, které jsou evidentně citlivé na pořadí (číselně to nestačí).
> Oprava chyby při ukládání aktivity

- admin/scripts/modules/aktivity/medailonky.php
https://trello.com/c/phluKwBP/1064-rozbit%C3%A9-medailonky
Když někdo chtěl vytvořit medailonek pro uživatele, který ho už měl, tak to padlo na fatal. Teď to přesměuje na detail.
> Nevyhazuj exception když medailonek už existuje

- model/Web/Loga.php
- web/index.php
- web/moduly/sponzori.php
- web/moduly/titulka.php
- web/sablony/blackarrow/sponzori.xtpl
- web/soubory/systemove/partneri/.gitignore
- web/soubory/systemove/partneri/RAZENI-VZOR.csv
- web/soubory/systemove/sponzori/.gitignore
- web/soubory/systemove/sponzori/RAZENI-VZOR.csv
- web/tridy/modul.php
https://trello.com/c/cmAKkTlf/881-%C5%99azen%C3%AD-log-sponzor%C5%AF-a-partner%C5%AF-na-webu
Vzorové soubory pro řazení log na webu.
> 881 řazení log sponzorů a partnerů na webu

- admin/scripts/modules/prava/_prava_jedne_role.php
- admin/scripts/zvlastni/reporty/neprihlaseni-vypraveci.php
- migrace/2023-05-04_01-prejmenovat-report-prihlaseni-a-ubytovani.php
https://trello.com/c/reFxrwM7/1062-report-neubytovan%C3%BDch-doplnit-role
> 1062 report neubytovaných doplnit role

- admin/scripts/modules/infopult.php
- admin/scripts/modules/uzivatel.php
- admin/scripts/modules/uzivatel.xtpl
- model/Shop/ShopUbytovani.php
- model/Uzivatel/Registrace.php
- model/uzivatel.php
https://trello.com/c/mAjVpWDZ/1076-ob%C4%8Danka-v-adminu
> Zobrazovat v adminu Infopultu údaje účastníka nutné pro ubytování

- admin/scripts/modules/reporty/quick-reporty.php
- admin/scripts/modules/reporty/reporty.php
- admin/scripts/modules/reporty/reporty.xtpl
- migrace/2023-05-17_01-moznost-omezit-format-quick-reportu.php
- migrace/pomocne/db-migrations/src/Report/SqlStruktura/ReportyQuickSqlStrukturaTest.php
- model/Report/SqlStruktura/ReportyQuickSqlStruktura.php
- model/db-form-gc.php
- model/knihovny/DbForm/db-form-field.php
- model/knihovny/DbForm/db-form.php
- model/knihovny/DbForm/dbff-checkbox.php
- model/knihovny/DbForm/dbff-text.php
```
@Jakub Korál Kubo cos nám to tam nasadil za obludu http://localhost/admin/reporty/quick-reporty?id=62
Lidi nám to otevírají v XLSX a generátor Excelu z toho páchá rituální sebevraždu.
Potřebujeme ho ještě?
Jakub Korál
Mají to testovat, když se to po nich chce. Ne Excel. Html only
```
Omezíme formát...
> Moznost quick reporty omezit na format

- admin/index.php
- admin/login.php
- admin/scripts/admin-menu.php
- admin/scripts/modules/aktivity/_export-import-hint.php
- admin/scripts/modules/aktivity/aktivity.php
- admin/scripts/modules/aktivity/medailonky.php
- admin/scripts/modules/aktivity/mistnosti.php
- admin/scripts/modules/aktivity/tagy.php
- admin/scripts/modules/finance/_paticka.php
- admin/scripts/modules/finance/finance.php
- admin/scripts/modules/finance/promlceni.php
- admin/scripts/modules/finance/slucovani.php
- admin/scripts/modules/prezence/tisk.php
- admin/scripts/modules/uzivatel.php
- admin/scripts/modules/web/chyby.php
- admin/scripts/modules/web/editace-stranek.php
- admin/scripts/modules/web/web.php
- admin/scripts/zvlastni/prezence-tisk.php
- model/Aktivita/OnlinePrezence/OnlinePrezenceHtml.php
- model/Aktivita/OnlinePrezence/templates/online-prezence.xtpl
- model/Login/Login.php
- model/Web/Info.php
- model/widget.php
- web/index.php
- web/tridy/menu.php
- web/tridy/modul.php
Abychom v odkazech na Trellu rovnou věděli, kam odkaz míří. Doteď bylo všude _Login_
> Prozrazovat nazev admin stranky pred loginem

- migrace/2023-02-10_01-zidle-na-role.php
- migrace/2023-05-26_01-platne_role_vcetne_historicke_ucasti.php
- model/Report/BfgrReport.php
- model/Role/Role.php
- model/uzivatel.php
https://trello.com/c/3ELHm8JJ/1088-revize-bfgr-gc-2023
> Fix BFGR histotie účasti

- model/Aktivita/Program.php
- web/moduly/program.php
- web/soubory/blackarrow/program/filtr-programu.js
- web/soubory/blackarrow/program/program.less
Rychlokvašný filtr programu https://gamecon.cz/program/ podle stavu aktivity
> Filtr programu

- admin/scripts/modules/_ubytovani-a-dalsi-obcasne-infopultakoviny-import-balicku.php
- admin/scripts/modules/_ubytovani-a-dalsi-obcasne-infopultakoviny-import-ubytovani.php
- admin/scripts/modules/_ubytovani-a-dalsi-obcasne-infopultakoviny-import-ubytovani.xtpl
- admin/scripts/modules/finance/finance.php
- admin/scripts/zvlastni/reporty/finance-report-ubytovani.php
- model/Shop/Predmet.php
- model/Ubytovani/SqlStruktura/UbytovaniSqlStruktura.php
- model/Ubytovani/Ubytovani.php
- model/uzivatel.php
- tests/Model/Ubytovani/SqlStruktura/UbytovaniSqlStrukturaTest.php
https://trello.com/c/7nUejFWd/977-oprava-importu-ubytov%C3%A1n%C3%AD
Něco jsme rozbili, něco přidali
> 977 oprava importu ubytování

- admin/files/design/styl.css
- admin/scripts/modules/aktivity/aktivity.php
- admin/scripts/modules/aktivity/aktivity.xtpl
- model/Aktivita/Aktivita.php
- model/Aktivita/OnlinePrezence/OnlinePrezenceHtml.php
- model/Aktivita/StavAktivity.php
- model/XTemplate/XTemplate.php
https://trello.com/c/kVWPqsSj/1092-tla%C4%8D%C3%ADtka-deaktivovat-a-odpublikovat
> Šéf programu může aktivitu odpublikovat

- web/sablony/blackarrow/gtag.xtpl
- web/sablony/blackarrow/index.xtpl
https://trello.com/c/wddqaRd8/1094-google-analytics-4
> GA4 skript

- model/uzivatel.php
https://trello.com/c/HZLOQcPn/991-rozbit%C3%A9-vyhled%C3%A1v%C3%A1n%C3%AD-%C3%BA%C4%8Dastn%C3%ADk%C5%AF
> Omnibox hledá příjmení i ve jméně

- model/uzivatel.php
https://trello.com/c/M1K4MTGA/971-vyprav%C4%9B%C4%8Dsk%C3%A1-skupina-se-v-adminu-zobrazuje-jako-%C3%BA%C4%8Dastn%C3%ADk
> Tmavě fialová a popis pro vypravěčskou skupinu

- model/Aktivita/Aktivita.php
https://trello.com/c/OyZ7Rzkw/1086-vysv%C4%9Btlivka-k-z%C3%A1me%C4%8Dku
> Přidána vysvětlivka k zámečku aktivity zamčené kapitánem týmu

- admin/scripts/modules/_ubytovani_tabulka.xtpl
- model/Cas/DateTimeCzTrait.php
- model/Shop/ShopUbytovani.php
- model/Shop/templates/shop-ubytovani.xtpl
- model/Uzivatel/Registrace.php
- web/moduly/registrace.php
- web/soubory/blackarrow/_spolecne/_zaklad.less
> 1024 text na stránce registrace

- admin/scripts/modules/statistiky.php
- model/Statistiky/Statistiky.php
https://trello.com/c/7blkRH1C/1101-aktuální-den-ve-statistikách
> Zvýraznění "dnes" ve statistikách

- model/Aktivita/OnlinePrezence/OnlinePrezenceHtml.php
- model/Aktivita/OnlinePrezence/templates/_nahradnik.xtpl
- model/Aktivita/OnlinePrezence/templates/_neprosel-infopultem.html
- model/Aktivita/OnlinePrezence/templates/_prosel-infopultem.html
- model/Aktivita/OnlinePrezence/templates/online-prezence-ucastnik.xtpl
- model/Aktivita/OnlinePrezence/templates/online-prezence.xtpl
- model/XTemplate/XTemplate.php
https://trello.com/c/UBOqY5Co/1103-p%C5%99idat-bod-do-n%C3%A1vodu-v-prezenc%C3%ADch
> Bod do návodu v online prezenci o nutnosti průchodu infopultem

- model/Shop/ShopUbytovani.php
- model/Shop/templates/shop-ubytovani.xtpl
https://trello.com/c/kLvqqnvz/1099-chyba-zobrazen%C3%AD-na-pokoji-s
> Opraveno zobrazení spolubydícícho s uvozovkami kolem přezdívky

- model/Aktivita/OnlinePrezence/templates/_neprosel-infopultem.html
- model/Aktivita/OnlinePrezence/templates/_prosel-infopultem.html
- model/Aktivita/OnlinePrezence/templates/online-prezence.xtpl
https://trello.com/c/UBOqY5Co/1103-p%C5%99idat-bod-do-n%C3%A1vodu-v-prezenc%C3%ADch
> Zkrácena žádost v online prezenci o poslání účastníka na infopult

- admin/files/design/styl.css
- migrace/2023-06-28_01-prazdne-staty-uctu-na-cekou-republiku.php
- model/Uzivatel/Registrace.php
- model/uzivatel.php
- web/soubory/blackarrow/_spolecne/_zaklad.less
https://trello.com/c/gnFCaVUa/1104-bug-s-pr%C3%A1zdn%C3%BDm-st%C3%A1tem
> 1104 bug s prázdným státem

- model/Shop/Shop.php
- model/Uzivatel/KategorieNeplatice.php
- model/report.php
- model/uzivatel.php
- tests/Model/Uzivatel/KategorieNeplaticeTest.php
- web/sablony/blackarrow/prihlaska.xtpl
https://trello.com/c/WqLjeZEm/969-automatizovat-odhlašování-neplatičů
> Už to vidím. Běží robot každých pět minut a padne to pol každém jednom odhlášení pár neplatičů. Chybka.
> 969 automatizovat odhlašování neplatičů

- .docker/php/conf.d/xdebug.ini
- model/Aktivita/Aktivita.php
- model/Aktivita/Program.php
- model/Aktivita/StavAktivity.php
- model/Aktivita/TypAktivity.php
- model/db-object.php
- model/funkce/fw-database.php
- model/lokace.php
- model/novinka.php
- model/obchod-mrizka-bunka.php
- model/obchod-mrizka.php
- model/stranka.php
- model/tag.php
- model/uzivatel.php
- web/moduly/program.php
- web/soubory/blackarrow/_spolecne/cookies-tools.js
- web/soubory/blackarrow/program-nahled/program-nahled.less
- web/soubory/blackarrow/program/filtr-programu.js
- web/soubory/blackarrow/program/program-prepnuti.js
https://trello.com/c/VYraquDp/1096-optimalizace-str%C3%A1nky-s-programem
> Všechny dny programu se vygenerují naráz

- model/Aktivita/AktivitaPrezence.php
- model/funkce/web-funkce.php
- nastaveni/nastaveni.php
https://trello.com/c/mw6OO7ez/988-e-mail-nedostaveni-na-aktivitu
> Přidat název aktivity do mailu Ty ty ty ses neodhlásil

- .docker/php/conf.d/php.ini
- admin/files/design/styl.css
- admin/files/promlceni.js
- admin/scripts/modules/finance/promlceni.php
- admin/scripts/modules/finance/promlceni.xtpl
- model/Aktivita/templates/tym-formular.xtpl
https://trello.com/c/iP8Rgicp/924-%C3%BAprava-ru%C5%A1en%C3%AD-z%C5%AFstatk%C5%AF
> Promlčení zůstatků umí filtrovat od do a ignorovat organizátory

- admin/scripts/modules/_infopult_ovladac.php
- admin/scripts/modules/infopult.php
- admin/scripts/modules/infopult.xtpl
- model/Uzivatel/Finance.php
- model/Web/Info.php
https://trello.com/c/WqLjeZEm/969-automatizovat-odhla%C5%A1ov%C3%A1n%C3%AD-neplati%C4%8D%C5%AF#comment-646dfaf3545efb2cb308ef4d
> Možnost na testu ručně připsat FIO ID a datum platby

- model/Uzivatel/Exceptions/HromadneOdhlasovaniJePrilisBrzyPoVlne.php
- model/Uzivatel/HromadneOdhlaseniNeplaticu.php
- tests/Uzivatel/HromadneOdhlaseniNeplaticuTest.php
https://trello.com/c/WqLjeZEm/969-automatizovat-odhla%C5%A1ov%C3%A1n%C3%AD-neplati%C4%8D%C5%AF#comment-64ab88ea30ae9d06de03a583
> Fix dalších hromadných odhlašování aby je neblokovaly proběhnnuté vlny

- admin/cron/jobs/mail_varovani_neplaticum_o_brzkem_odhlaseni.php
- model/Cas/DateTimeGamecon.php
- model/SystemoveNastaveni/SystemoveNastaveni.php
- model/Uzivatel/HromadneOdhlaseniNeplaticu.php
https://trello.com/c/WqLjeZEm/969-automatizovat-odhla%C5%A1ov%C3%A1n%C3%AD-neplati%C4%8D%C5%AF
Fix aby to dokázalo odeslat varování neplatičům tři dny před hromadným odhlašováním.
> Fix odeslání varovného emailu neplatičům tři dny před hromadným odhlašováním

- admin/scripts/zvlastni/reporty/stravenky-bianco.php
- admin/scripts/zvlastni/reporty/stravenky.php
- admin/scripts/zvlastni/reporty/stravenky.xtpl
- admin/scripts/zvlastni/reporty/zazemi-a-program-potvrzeni-pro-navstevniky-mladsi-patnacti-let.php
https://trello.com/c/HRzR7ccv/1108-oprava-report%C5%AF
> Drobné opravy reportů

- admin/scripts/modules/_infopult_ovladac.php
- admin/scripts/modules/infopult.php
- admin/scripts/modules/infopult.xtpl
- migrace/2023-07-06_01-priznak-uctu-z-rychloregistrace.php
- model/SystemoveNastaveni/AnonymizovanaDatabaze.php
- model/Uzivatel/SqlStruktura/UzivatelSqlStruktura.php
- model/uzivatel.php
Přišel, nepřihlásil, odešel, nechceme.
_"Čárka na futra"_ za každého _"Jdu jenom do deskoherny"_.
> Rychloregistrace pro cumily

- admin/scripts/zvlastni/reporty/report-infopult-ucastnici-balicky.php
- admin/scripts/zvlastni/reporty/report-infopult-ucastnici-balicky.xtpl
- admin/scripts/zvlastni/reporty/zazemi-a-program-seznam-ucastniku-a-tricek-grouped.php
- admin/scripts/zvlastni/reporty/zazemi-a-program-seznam-ucastniku-a-tricek.php
- migrace/2023-07-11_01-report-balicku-bez-xlsx.php
- migrace/2023-07-12_01-skryt-report-tricek-negrouped.php
- model/Shop/KategoriePredmetu.php
- model/Shop/Predmet.php
https://trello.com/c/HRzR7ccv/1108-oprava-report%C5%AF
> 1108 oprava reportů

- admin/scripts/modules/infopult.xtpl
- admin/templates/uzivatel.xtpl
https://trello.com/c/mAjVpWDZ/1076-ob%C4%8Danka-v-adminu#comment-64a74674f00678ab31b6658b
> 1076 občanka v adminu oprava potvrzení zrušení pracovního dlužníka

- model/Cas/DateTimeCzTrait.php
- tests/Model/Cas/DateTimeCzTraitTest.php
Gamecon\Cas\DateTimeCz::zaokrouhlitNaHodinyNahoru(): Return value must be of type Gamecon\Cas\DateTimeCzTrait, Gamecon\Cas\DateTimeCz returned
http://admin.gamecon.cz/prezence « https://admin.gamecon.cz/uzivatel
> Nefunguje admin prezence

- admin/scripts/modules/infopult.php
https://trello.com/c/mAjVpWDZ/1076-ob%C4%8Danka-v-adminu
Prázdná hláška při kliknutí na Přijel a Dát materiály. Místo seznamu nedostatků pouze tečka.
> Nezobrazovat potvrzovací okno když nejsou problémy

- admin/files/design/online-prezence.css
- admin/files/online-prezence/online-prezence-keep-alive.js
- admin/files/online-prezence/online-prezence-sort.js
- admin/index.php
- model/Aktivita/OnlinePrezence/OnlinePrezenceHtml.php
- model/Aktivita/OnlinePrezence/templates/online-prezence-ucastnik.xtpl
- model/Aktivita/OnlinePrezence/templates/online-prezence.xtpl
- model/uzivatel.php
https://trello.com/c/Bek4GduQ/1126-zp%C4%9Btn%C3%A1-vazba-k-prezen%C4%8Dk%C3%A1m-2023-chyby-a-d%C5%AFle%C5%BEit%C3%A9-zm%C4%9Bny
> Zpětná vazba k prezenčkám 2023

- admin/scripts/zvlastni/reporty/finance-lide-v-databazi-a-zustatky.php
- composer.lock
- model/Report/BfgrReport.php
- model/Report/FinanceLideVDatabaziAZustatky.php
- model/Report/KonfiguraceReportu.php
- model/SystemoveNastaveni/SystemoveNastaveni.php
- model/report.php
- model/uzivatel.php
https://trello.com/c/gz0OVLri/1090-report-lid%C3%A9-v-db-z%C5%AFstatky-historick%C3%A1-%C3%BA%C4%8Dast
> Historická účast v samostatných sloupcích pro report zůstatků

- composer.lock
- migrace/9999_01-letosni-role-krome-ucasti-endless.php
- model/uzivatel.php
Přidáno upozornění pro infopult že účastník je brigádník a má podepsat papír o převzetí bonusu.
> Upozorneni na brigadnicky podpis

- admin/scripts/zvlastni/reporty/update-zustatku.php
- nastaveni/nastaveni.php
https://trello.com/c/dF7V3TZX/1149-p%C5%99eklopit-ro%C4%8Dn%C3%ADk-uzav%C5%99en%C3%AD-ro%C4%8Dn%C3%ADku-2023
> Přepnutí ročníku na 2024 a úpravy překlápěcího skriptu

- admin/scripts/api/obchod-mrizky-view.php
- admin/scripts/api/predmety.php
https://trello.com/c/skvnFhln/1152-bezpe%C4%8Dnostn%C3%AD-d%C3%ADra-api-na-adminu-jsou-dostupn%C3%A9-bez-p%C5%99ihl%C3%A1%C5%A1en%C3%AD
Původně jsem chtěl přesunout API do modulů, aby jádro začalo načítat security (ty magické komentáře na začátku PHP souboru), ale bylo by kolem toho příliš práce.
Nakonec jsem zůstal u prosté ruční kontroly práv na začátku každého API skriptu.
> 1152 bezpečnostní díra api na adminu jsou dostupné bez přihlášení

- admin/scripts/zvlastni/reporty/update-zustatku.php
https://trello.com/c/0vElz84M/1162-smazat-%C4%8D%C3%ADslo-op-a-chci-b%C3%BDt-na-pokoji-s
> Při překlápění ročníku mazat i OP

- model/uzivatel.php
https://trello.com/c/Bek4GduQ/1126-zp%C4%9Btn%C3%A1-vazba-k-prezen%C4%8Dk%C3%A1m-2023-chyby-a-d%C5%AFle%C5%BEit%C3%A9-zm%C4%9Bny#comment-660359d8a1bee685673e1791
> spalo by se mi lépe, kdybych věděla, že to na ostré našeptávat bude… =D
Vrtáš do toho správně, je tam chyba.
Rušili jsme “právo” Dorazil na GC a nechali jenom roli. Ale v některých selectech z databáze to zůstalo po staru.v
> 1126 Fix načítání uživatelů přítomných na GC pro Online prezenci

- .docker/Dockerfile
- .docker/docker-build.sh
- docker-compose.yml
- PHP zvednuto pro lokální vývoj na 8.3
- do Dockeru přidán `yarn`
> Přehodit PHP v Dockeru na 8.3

- nastaveni/nastaveni.php
https://trello.com/c/ZgMKYigt/448-oprava-automatick%C3%BDch-mail%C5%AF#comment-660daa346f2e96b8106f6cd1
> 448 Fix některých textů pro návštěvníky

- .gitignore
- migrace/2024-04-05_01-import-mistnosti-2024.php
https://trello.com/c/diQHpAlU/1168-import-m%C3%ADstnost%C3%AD
> 1168 Import místností pro 2024

- admin/scripts/modules/finance/promlceni.php
- model/Report/KonfiguraceReportu.php
- model/report.php
Aby se nám z `2012,2017` nestalo číslo 2012.2017
> Fix export seznamu k promlčení aby dva ročníky nebyl jeden float

- web/moduly/api/aktivityProgram.php
https://trello.com/c/AYvfZrhA/1159-program-dod%C4%9Blky
> program - nahled vypraveci

- model/Shop/ShopUbytovani.php
- model/Shop/templates/shop-ubytovani.xtpl
https://trello.com/c/QuGFcEkH/1145-opravy-p%C5%99ihl%C3%A1%C5%A1ky-2024
> Opravy přihlášky 2024

- model/Uzivatel/Finance.php
- web/moduly/finance.php
- web/moduly/prihlaska/prihlaska.php
https://trello.com/c/pBiUyS7Q/1112-sk-qr-k%C3%B3d-je-k-ni%C4%8Demu
> 1112 QR platbu zobrazovat jen českým účastníkům kvůli nepodporované QR SEPA platbě

- model/Shop/ShopUbytovani.php
- model/Shop/templates/shop-ubytovani.xtpl
- model/SystemoveNastaveni/SystemoveNastaveni.php
- nastaveni/nastaveni.php
https://trello.com/c/QuGFcEkH/1145-opravy-p%C5%99ihl%C3%A1%C5%A1ky-2024
> 1145 spacaky only vypnutelne

- migrace/2024-05-05_01-import-mistnosti-2024-vcetne-budovy-c.php
https://trello.com/c/mhJ10X1X/1182-reimport-mistnosti#comment-663526aa797c161b7c2d13e3
> 1182 Přejmenovat a přesunout některé místnosti, přidat nové aneb Vítej zpět budovo C

- admin/scripts/modules/_import-eshopu.php
- admin/scripts/zvlastni/reporty/finance-report-eshop.php
- migrace/2024-05-05_02-kod-predmetu-a-typu-predmetu.php
- model/Shop/SqlStruktura/PredmetSqlStruktura.php
- model/funkce/funkce.php
- tests/Model/Uzivatel/FinanceCenaPredmetuTest.php
- tests/Uzivatel/HromadneOdhlaseniNeplaticuTest.php
https://trello.com/c/2npgtILj/1181-k%C3%B3d-p%C5%99edm%C4%9Btu-a-k%C3%B3d-typu-p%C5%99edm%C4%9Btu-pro-eshop
Import e-shopu tak nyní může přejmenovat položky.
> 1181 Přidat kód produktu

- web/moduly/titulka.php
- web/sablony/blackarrow/titulka.xtpl
https://trello.com/c/arSXwR50/1091-opravy-textu-na-webu
> Automaticky zjišťovat počty minulých účastníků a aktivit

- web/moduly/titulka.php
Zaokrouhlování počtu aktivit na stovky bylo moc hrubé, zaokrouhlíme na desítky.
> 1091 opravy textu na webu

- admin/scripts/modules/_import-eshopu.php
- migrace/2024-05-06_01-fix-kod-predmetu-na-neunikatni.php
https://trello.com/c/HOsfptG2/372-nahrat-e-shop#comment-6638832596b92b8c0695051c
> 1181 Změnit kód předmětu aby označoval stejný předmět napříč ročníky

- admin/scripts/modules/_uzivatel_ovladac.php
- model/Shop/Shop.php
https://trello.com/c/RTnrvrIN/1190-j%C3%ADdlo-z-objedn%C3%A1vky-se-neulo%C5%BE%C3%AD
> 1190 jídlo z objednávky se neuloží

- model/Aktivita/Aktivita.php
- model/Web/Loga.php
- model/nahled.php
- model/obrazek.php
- model/uzivatel.php
- web/moduly/prihlaska/prihlaska.php
https://trello.com/c/AVN0IcA0/1189-p%C5%99ihl%C3%A1%C5%A1ka-n%C3%A1hledy-pro-eshop
> 1189 Načítat obrázky pro eshop přímo z adresáře

- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-ostra.yml
- .github/workflows/run-tests.yml
- Dockerfile
- composer.json
- docker-compose.dev.yml
- docker-compose.yml
Chceme-li být up-to-date se serverem...
> Update verzí PHP a MariaDB

- model/Aktivita/AkcePrihlaseniStavy.php
- model/Aktivita/AktivitaPrezence.php
- model/Aktivita/SqlStruktura/AkcePrihlaseniStavySqlStruktura.php
- model/Aktivita/StavPrihlaseni.php
- model/Hlaska/Hlaska.php
- model/uzivatel.php
- nastaveni/.gitignore
- nastaveni/hlasky/nastaveni-hlasky-subst.php
- nastaveni/hlasky/nastaveni-hlasky.php
- nastaveni/nastaveni.php
- udrzba/_pomocne.php
https://trello.com/c/mw6OO7ez/988-e-mail-nedostaveni-na-aktivitu-ne%C5%99%C3%ADk%C3%A1-na-jakou-aktivitu
https://docs.google.com/document/d/1zsmBXexf_rUptW42ryNCffu6il1U6GZKVQddo1Idqak/edit
> Ujasněn text emailu o nedostavení se na aktivitu

- migrace/9999_01-letosni-role-krome-ucasti-endless.php
- model/Statistiky/Statistiky.php
https://trello.com/c/41eZjZjn/1193-admin-statistiky-po%C4%8Det-vyprav%C4%9B%C4%8D%C5%AF
> 1193 Odebírat loňské role ze statistik letošní účasti

- web/sablony/blackarrow/titulka.xtpl
- web/soubory/blackarrow/gchlavicka/gchlavicka.less
[Trello](https://trello.com/c/FczNo9c4/1179-propaga%C4%8Dn%C3%AD-video-na-homepage)
> 1179 Propagační video na homepage

- admin/cron/fio_stazeni_novych_plateb.php
- admin/scripts/modules/finance/platby.php
- admin/scripts/modules/finance/platby.xtpl
- migrace/2024-05-17_opravit-popis-parovaciho-textu-pro-vs-odchozi-platby.php
- model/Uzivatel/Platba.php
- model/Uzivatel/Platby.php
- model/fio-platba.php
https://trello.com/c/Cg3utgRm/1198-vracení-přeplatku-účastníka-dotaz
> 1198 Přehled nespárovanýcyh plateb do adminu

- model/Aktivita/Aktivita.php
- model/db-object.php
- web/moduly/wp-json/wp/v2/users.php
https://trello.com/c/dsHFRSwR/1210-nefunguje-program-v-adminu
> 1210 nefunguje program v adminu

- model/Uzivatel/Registrace.php
https://trello.com/c/peWueAi9/1209-doplnit-informaci-o-d%C5%AFvodu-pohlav%C3%AD-nastaven%C3%AD-profilu
> 1209 Vysvětlující text proč potřebujeme znát pohlaví

- web/moduly/finance.php
- web/moduly/prihlaseni.php
- web/moduly/prihlaska/prihlaska.php
https://trello.com/c/3dHD6pV3/1200-matouc%C3%AD-tich%C3%A9-p%C5%99esm%C4%9Brov%C3%A1n%C3%AD-nep%C5%99ihl%C3%A1%C5%A1en%C3%A9ho
> 1200 matoucí tiché přesměrování nepřihlášeného

- model/Uzivatel/Registrace.php
- web/soubory/blackarrow/formular/formular.less
https://trello.com/c/peWueAi9/1209-doplnit-informaci-o-d%C5%AFvodu-pohlav%C3%AD-nastaven%C3%AD-profilu#comment-666232427f52123bbb82c64f
> 1209 Fix pozice tooltipu k pohlaví na větších obrazovkách

- web/sablony/blackarrow/aktivity.xtpl
- web/soubory/blackarrow/aktivity/aktivity.less
Velká anotace aktivity se otevře i při kliknutí na nadpis/obrázek.
https://trello.com/c/JrMJR5Fm/818-sekce-otev%C3%ADr%C3%A1n%C3%AD-a-zav%C3%ADr%C3%A1n%C3%AD-velk%C3%BDch-anotac%C3%AD
> 818 sekce otevírání a zavírání velkých anotací

- admin/scripts/modules/infopult.xtpl
- model/Aktivita/OnlinePrezence/templates/online-prezence.xtpl
- model/pomoc-texty.php
- model/pomoc.xtpl
- nastaveni/hlasky/nastaveni-hlasky-subst.php
- nastaveni/hlasky/nastaveni-hlasky.php
- web/sablony/blackarrow/prihlaska.xtpl
První návrh úpravy textů inspirovanou https://github.com/gamecon-cz/gamecon/pull/521
> 1204-úpravy-textů-z-discordu

- .github/workflows/run-tests.yml
- admin/scripts/modules/finance/nesparovane-platby.php
- admin/scripts/modules/finance/nesparovane-platby.xtpl
- admin/stare-routy.php
- migrace/2024-06-22_01-ukladat-skrytou-poznamku-k-platbam.php
- model/Uzivatel/Platba.php
- model/Uzivatel/Platby.php
- model/Uzivatel/SqlStruktura/PlatbySqlStruktura.php
- model/chyba.php
https://trello.com/c/SwxdFLWY/1224-sp%C3%A1rovat-platbu-bez-vs-pro-956
> Možnost pro CFO spárovat nespárovanou platbu

- admin/scripts/modules/_shop.php
- model/Shop/Shop.php
Taky opravuje závažnou chybu v KFC, kdy systém evidoval vždy pouze první prodaný předmět při prodeji více souběžně, ale nijak to nedal najevo.
> 1184 oprava reportu finance příjmy a výdaje infopulťáka

- model/Aktivita/Aktivita.php
https://trello.com/c/PyfRBoU1/1197-bug-navazuj%C3%ADc%C3%ADch-aktivit#comment-667af121db95c82d355cb5c1
> 1197 bug navazujících aktivit

- model/Vyjimkovac/vyjimkovac-omluva.xtpl
- web/sablony/blackarrow/index.xtpl
- web/sablony/blackarrow/prihlaska.xtpl
Převedení discordu na Discord Acc
> Změna discord odkazů

- web/moduly/discord.php
Rychlé přesměrování cool vzhled
> 1254-gameconcz-discord

- web/sablony/blackarrow/titulka.xtpl
Nevím co se tam stalo, že je tam tolik změn. Možná mi to odstranilo konce řádků?
> 1110-opravy-home-page

- admin/scripts/modules/aktivity/_Import/ImportValuesSanitizer.php
- model/Aktivita/Program.php
Program by už neměl padat na nedostatek paměti pokud aktivita začne dřív než začíná program ten den, a import by ty hodnoty taky už neměl vůbec pustit.
https://trello.com/c/Y7IRu7LC/1219-oprava-program-po-m%C3%ADstnostech
> Základní ošetření 1219-oprava-program-po-místnostech

- admin/cron/_cron_job.php
- admin/cron/_odlozeny_cas.php
- admin/cron/jobs/materializace_roli_podle_rocniku.php
- admin/scripts/zvlastni/reporty/role-podle-rocniku.php
- migrace/2024-06-11_01-serial-pro-log-roli.php
- migrace/2024-06-11_02-sql-funkce-pro-konec-gc.php
- migrace/2024-06-11_03-uzivatele-role-podle-rocniku.php
- migrace/2024-06-13_01-report-role-podle-rocniku.php
- model/Role/RolePodleRocniku.php
- model/uzivatel.php
https://trello.com/c/xNJPqR3Y/1170-oprava-statisitk-a-xxxxadmin
> 1170 Přidán zdroj rolí podle roku od 2022 dále

- web/sablony/blackarrow/index.xtpl
- web/sablony/blackarrow/titulka.xtpl
- přidání alt atributů
- lazy loading
- přidání meta description
> 1272 - Základní SEO

- .github/workflows/autorebase.yml
```
Checking out head ref '1158-rozpočtový-report-vytvořit-2'.
Setting committer to match the last commit on the head ref.
Rebasing on base ref 'main'.
Pushing changes to head ref '1158-rozpočtový-report-vytvořit-2'
/usr/bin/git push --force-with-lease 627ac467-ea79-4ab7-9d75-968b7d480e50 HEAD:1158-rozpočtový-report-vytvořit-2
To https://github.com/Adrijaned/gamecon
! [remote rejected]   HEAD -> 1158-rozpočtový-report-vytvořit-2 (refusing to allow a GitHub App to create or update workflow `.github/workflows/autorebase.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/Adrijaned/gamecon'
Error: The process '/usr/bin/git' failed with exit code 1
```
> GitHub autorebase

- model/Uzivatel/Finance.php
Gandalf verze
https://trello.com/c/MQzX4W9d/1242-vyprav%C4%9B%C4%8D-se-odhl%C3%A1s%C3%AD-z-gameconu
> 1242-vypravěč-se-odhlásí-z-gameconu

- Makefile
- docker-compose.yml
- model/fio-platba.php
- tests/Model/FioPlatbaTest.php
https://trello.com/c/eKCP5POn/1215-zmena-bankovni-api-u-fio#comment-67ca9b8abe14e804151a5106
> 1215 Změna URL adresy pro Fio API

- admin/cron/fio_stazeni_novych_plateb.php
- admin/files/disable-and-show-loading-on-click-1.2.js
- admin/files/reload-fio-1.0.js
- admin/files/zablikej-1.0.js
- admin/scripts/api/reload-fio.php
- admin/scripts/modules/finance/hromadne-odhlasovani.php
- admin/scripts/modules/infopult.php
- admin/scripts/modules/infopult.xtpl
- admin/scripts/zvlastni/program-uzivatele.php
- admin/templates/main.xtpl
- model/Uzivatel/Finance.php
- model/Uzivatel/Platby.php
- model/fio-platba.php
- model/funkce/funkce.php
- tests/Model/FioPlatbaTest.php
- tests/Model/Uzivatel/KategorieNeplaticeTest.php
https://trello.com/c/4ExsTDlQ/1298-tla%C4%8D%C3%ADtko-na-okam%C5%BEit%C3%A9-sta%C5%BEen%C3%AD-okam%C5%BEit%C3%A9-platby
> 1298 Tlačítko na aktualizaci plateb v adminu

- web/moduly/sponzori.php
- web/sablony/blackarrow/index.xtpl
- web/soubory/blackarrow/sponzori/sponzori.less
https://trello.com/c/y7A4eXOY/1143-nov%C3%A1-str%C3%A1nka-partne%C5%99i
> 1143-nová-stránka-partneři

- admin/scripts/modules/_import-eshopu.php
- model/Vyjimkovac/VyjimkovacChyba.php
Fix importu po té, co jsme nedávno odebírali nepotřebné sloupce z DB
> 414 Fix import eshopu po smazání sloupce v DB

- web/moduly/titulka.php
- web/sablony/blackarrow/titulka.xtpl
- web/soubory/blackarrow/april2025/april2025.css
- web/soubory/blackarrow/april2025/april2025.js
https://trello.com/c/gfwQX4p2/1314-apr%C3%ADlov%C3%BD-ft%C3%ADpek-2025
> 1314-aprílový-ftípek-2025

- admin/cron/fio_stazeni_novych_plateb.php
- admin/cron/jobs/mail_cfo_nesparovane_platby.php
- admin/cron/jobs/synchronizace_historickych_plateb.php
- admin/scripts/api/reload-fio.php
- admin/scripts/modules/finance/nesparovane-platby.php
- admin/scripts/modules/finance/nesparovane-platby.xtpl
- bin-docker/_tty.sh
- bin-docker/composer
- bin-docker/docker-bash
- bin-docker/php
- bin-docker/yarn
- migrace/2025-04-03_09-42-18-rozsireni-platby.php
- model/Aktivita/AkcePrihlaseniStavy.php
- model/Aktivita/StavAktivity.php
- model/Kfc/ObchodMrizka.php
- model/Kfc/ObchodMrizkaBunka.php
- model/Pravo.php
- model/Role/Role.php
- model/Shop/Predmet.php
- model/Uzivatel/Platba.php
- model/Uzivatel/Platby.php
- model/Uzivatel/SqlStruktura/PlatbySqlStruktura.php
- model/db-object.php
- model/e-p-d-o.php
- model/fio-platba.php
- model/lokace.php
- model/tag.php
- tests/Model/FioPlatbaTest.php
https://trello.com/c/vablCMKI/1270-finance-platby-p%C5%99idat-vs-a-jm%C3%A9no
> 1270 Přidat VS a protiúčet do přehledu nespárovanách plateb

- admin/scripts/zvlastni/reporty/stavy-uctu-ucastniku.php
- migrace/2024-11-07_01-report-stavu-uctu-ucastniku.php
- model/Report/StavyUctuUcastniku.php
https://trello.com/c/yDo9gWqI/1278-report-z%C5%AFstatk%C5%AF-v%C5%A1ech-u%C5%BEivatel%C5%AF
> Report zustatku

- web/index.php
- web/sablony/blackarrow/index.xtpl
přidání odkazu do patičky 
https://trello.com/c/1qU0vyZ2/1266-qr-page-socky-links
> 1266-qr-page-socky-links

- web/index.php
- web/sablony/blackarrow/index.xtpl
https://trello.com/c/1qU0vyZ2/1266-qr-page-socky-links
> Odkaz na QRka v patičce zobrazovat jen pro přihlášené organizátory

- admin/files/hinted-1.0.js
- admin/scripts/modules/aktivity/aktivity.xtpl
- admin/templates/main.xtpl
https://trello.com/c/H7X3Ocv6/1305-p%C5%99ehled-aktivit-n%C3%A1pov%C4%9Bdy-se-vyl%C3%ADzaj%C3%AD-ze-str%C3%A1nky
> překrývání hintu oprava

- migrace/2025-03-26-odebrani-dobrovolnik.php
- migrace/2025-03-31-tricko-zdarma-pravo.php
- migrace/2025-04-13-UBYTOVANI_NEDELNI_NOC.php
- model/Pravo.php
- model/Shop/ShopUbytovani.php
- model/Uzivatel/Finance.php
- model/cenik.php
- nastaveni/verejne-nastaveni-beta.php
https://trello.com/c/zleM7C7k/1292-role-mini-org
> dodělky mini org

- web/sablony/blackarrow/menu.xtpl
Zakomentování prokliku pro média, stránka nevypadá dokončeně
> zakomentování-pro-média

- admin/scripts/modules/aktivity/aktivity.php
- admin/scripts/modules/finance/ruseni-storna.php
- model/Aktivita/Aktivita.php
- model/Aktivita/Program.php
https://trello.com/c/Gv91OIIA/1207-v-emailech-m%C3%A1-no%C4%8Dn%C3%AD-aktivita-%C5%A1patn%C3%A9-datum
> denCas zobrazuje skutečný den místo programového

- web/moduly/aktivity.php
- web/sablony/blackarrow/aktivity.xtpl
- web/soubory/blackarrow/aktivity/aktivity.less
https://trello.com/c/URFt3Rct/1312-%C3%BAprava-str%C3%A1nek-aktivit
> 1312-úprava-stránek-aktivit

- admin/scripts/modules/aktivity/_Import/Activities/ImportStepResult.php
- admin/scripts/modules/aktivity/_Import/Activities/ImportValuesSanitizer.php
https://trello.com/c/J4SqVsqm/1323-na-bet%C4%9B-nefunguje-hromadn%C3%BD-import-aktivit
Kód správně poznal, že datum je v divném formátu, ale pak si myslel, že je to vlastně OK.
> 1323 Fix crash když se nepodaří parsovat datum aktivity při importu

- web/index.php
- web/sablony/blackarrow/menu.xtpl
požadavky v komentáři na kartě https://trello.com/c/cY4YElXR/392-kompletn%C3%AD-revize-webu#
> odkrytí prokliku pro media a oprava překlepu

- admin/scripts/modules/aktivity/_Import/Activities/ActivityImporter.php
- admin/scripts/modules/aktivity/_Import/Activities/ImportValuesSanitizer.php
- model/Aktivita/Aktivita.php
- model/Aktivita/templates/editor-aktivity.xtpl
https://trello.com/c/FTKdqmpW/1330-chyby-v-exportu-importu-aktivit
> Fix importu aktivit co končí o půlnoci a fix nechtěného rušení korekce

- admin/scripts/modules/aktivity/_Import/ImporterUcastnikuNaAktivitu.php
- admin/scripts/modules/aktivity/_import-ucastniku.php
- admin/scripts/modules/aktivity/export-import-ucastniku.xtpl
- docker-compose.yml
- migrace/2025-03-21-akce-typy.php
- model/Aktivita/Aktivita.php
- nastaveni/hlasky/nastaveni-hlasky.php
- tests/Db/data/README.md
https://trello.com/c/7YMLryNa/1055-import-%C3%BA%C4%8Dastn%C3%ADk%C5%AF-na-aktivity
> 1055 import účastníků na aktivit

- web/soubory/blackarrow/shop/shop-ubytovani.less
[oprava delšího sloupce](https://trello.com/c/Hd1zUAfg/1291-omezen%C3%AD-ubytov%C3%A1n%C3%AD-pro-%C3%BA%C4%8Dastn%C3%ADky-na-3-noci) oprava stylyzování, řešená zde
> delší popisek sloupce ubytování

- model/Uzivatel/Finance.php
- web/moduly/finance.php
https://trello.com/c/pxdMmjCu/1225-na-finance-zobrazit-slov%C3%A1k%C5%AFm-i-cz-platebn%C3%AD-mo%C5%BEnosti
> 1225-na-finance-zobrazit-slovákům-i-cz-platební-možnosti

- web/moduly/prihlaska/prihlaska.php
- web/sablony/blackarrow/prihlaska.xtpl
doplnění textu viz https://trello.com/c/Hd1zUAfg/1291-omezen%C3%AD-ubytov%C3%A1n%C3%AD-pro-%C3%BA%C4%8Dastn%C3%ADky-na-3-noci
> text-ubytko-2025

- web/soubory/blackarrow/aktivity/aktivity.less
https://trello.com/c/Z1BurKSd/1329-divn%C3%A9-zobrazen%C3%AD-medailonk%C5%AF-na-webu
> 1329-divné-zobrazení-medailonků-na-webu

- model/Shop/Predmet.php
- model/Shop/ShopUbytovani.php
- model/Shop/templates/shop-ubytovani.xtpl
> Hotfix na objednání tří nocí naráz

- admin/scripts/modules/aktivity/aktivity.php
- model/Aktivita/Aktivita.php
https://trello.com/c/zh6nllxO/1336-mdrd-nastaven%C3%AD-semifin%C3%A1lov%C3%BDch-limit%C5%AF-na-p%C5%99ihla%C5%A1ov%C3%A1n%C3%AD
> 1336 Automaticky limitovat počet přihlášených týmů na semifinále mDrD podle počtu vypravěčů

- admin/scripts/zvlastni/reporty/finance-report-sirien.php
- migrace/2024-06-28_uzitecne-funkce.php
- migrace/2024-07-01_sirienuv-rozpocotvy-report.php
- migrace/2024-07-04_kody-typu-akci.php
- model/Aktivita/Aktivita.php
- model/Aktivita/SqlStruktura/TypAktivitySqlStruktura.php
- model/tag.php
https://trello.com/c/R15pukcf/1158-rozpo%C4%8Dtov%C3%BD-report-vytvo%C5%99it
> 1158-rozpočtový-report-vytvořit

- model/Uzivatel/Finance.php
Pokus č. 2 https://trello.com/c/VSLwgbdv/1343-bug-financ%C3%AD-vyprav%C4%9B%C4%8De-karlochyba
> Fix započítání bonusu

- admin/scripts/zvlastni/reporty/slevy.php
- migrace/2025-06-07-14_41-report-slev.sql
https://trello.com/c/FXgPFYEj/1313-vytvo%C5%99it-report-slev
> 1313-vytvořit-report-slev

- admin/scripts/modules/uzivatel.php
- model/Shop/Shop.php
- model/Shop/ShopUbytovani.php
Protože v class nechceme používat global variables
> Ubytování přes kapacitu pro CFO čistěji

- admin/scripts/modules/aktivity/_Import/Activities/ImportObjectsContainer.php
https://trello.com/c/9bjdf1f0/1341-import-aktivit-zam%C4%9B%C5%88uje-n%C4%9Bkter%C3%A9-%C5%A1t%C3%ADtky
> 1341 Odstranění importu tagů podle ID z importu aktivit

- admin/scripts/modules/uzivatel.php
- admin/scripts/modules/uzivatel.xtpl
- model/Shop/templates/shop-ubytovani.xtpl
- web/soubory/blackarrow/shop/shop-ubytovani.js
https://trello.com/c/lfiYxDFM/1354-funkci-pro-ubytko-p%C5%99es-%C4%8D%C3%A1ru-p%C5%99idat-p%C5%99ehodit-na-%C5%A1%C3%A9fa-infa
> 1354-funkci-pro-ubytko-přes-čáru-přidat-přehodit-na-šéfa-infa

- model/SystemoveNastaveni/SystemoveNastaveni.php
- model/funkce/funkce.php
- web/moduly/finance.php
Kartička neexistuje. Ve financích se zobrazuje špatný datum.
> Oprava času do kdy zaplatit

- model/chyba.php
https://trello.com/c/DCJbXXz5/1367-admin-zru%C5%A1it-infoprou%C5%BEky-na-jedno-kliknut%C3%AD-kamkoliv
> 1367-admin-zrušit-infoproužky-na-jedno-kliknutí-kamkoliv

- admin/scripts/modules/infopult.php
- admin/scripts/modules/infopult.xtpl
- model/Finance/QrPlatba.php
odstranění data, přidání příznaku a odstranění pole
https://trello.com/c/4ExsTDlQ/1298-tla%C4%8D%C3%ADtko-na-okam%C5%BEit%C3%A9-sta%C5%BEen%C3%AD-okam%C5%BEit%C3%A9-platby
> 1298-tlačítko-na-okamžité-stažení-okamžité-platby

- model/SystemoveNastaveni/SystemoveNastaveni.php
- web/moduly/titulka.php
> máme rozbité počítadla
https://trello.com/c/EBWcB0W1/1371-fix-po%C4%8Det-spokojen%C3%BDch-%C3%BA%C4%8Dastn%C3%ADk%C5%AF-na-titulce
> Fix pocet spokojenych ucastniku a aktivit na titulce

- admin/scripts/modules/finance/promlceni.php
- admin/scripts/modules/finance/promlceni.xtpl
https://trello.com/c/1c1Zv6ud/1279-opravit-finance-promlcen%C3%AD
> 1279 Odstraněn export seznamu k promlčení do XLSX

- Makefile
- admin/scripts/modules/aktivity/aktivity.php
- admin/scripts/modules/aktivity/aktivity.xtpl
- admin/scripts/modules/aktivity/upravy.php
- bin/phpunit.sh
- model/Aktivita/Aktivita.php
- model/funkce/fw-database.php
- model/uzivatel.php
- tests/Symfony/EntityLegacyComparisonTest.php
- vendor/composer/installed.php
https://trello.com/c/MqZT3G4a/1331-oprava-za%C5%A1krt%C3%A1v%C3%A1tka-na-korektury
> 1331-oprava-zaškrtávátka-na-korektury

- .github/workflows/autorebase.yml
- .github/workflows/deploy-beta.yml
- .github/workflows/deploy-ostra.yml
- .github/workflows/run-tests.yml
- admin/scripts/modules/finance/slucovani.xtpl
- admin/scripts/zvlastni/reporty/duplicity.php
- migrace/2025-06-03-xlsx-pro-report-slucovani.php
- model/uzivatel.php
https://trello.com/c/HGKziykz/1283-report-duplicitn%C3%AD-u%C5%BEivatel%C3%A9
> 1283-report-duplicitní-uživatelé

- admin/scripts/modules/finance/nesparovane-platby.php
- migrace/2025-09-22_01-foreign-keys-platby-id-uzivatele.sql
- model/Uzivatel/UzivatelSlucovani.php
https://trello.com/c/GFw4SEFq/1379-ztracen%C3%A1-platba-vs-id-6200
> 1379 Zakázat smazání platby při mazání uživatele
