- nastaveni/nastaveni.php
ČNB uvolnila kurz o pár měsíců dříve než avizovala a vytváří to nedoplatky u Slováků. Snižujeme o půl koruny dolů.
> kurz EUR - 25,5

- admin/scripts/modules/uvod.php
- admin/scripts/modules/uvod.xtpl
- admin/scripts/zvlastni/reporty/celkovy-report.php
- migrace/021.php
- model/finance.php
Do adminu přibyla možnost "Připsané slevy"
Na stránce úvod:
V celkovém reportu:
Slevy **by se** neměli přenášt mezi léty. Resp. zůstatek z minulých let se bere z `uzivatele_hodnoty`.`zustatek` a tam si úplně nejsem přesně jist jak se to chová. Takže prosím o kontrolu @godric-cz nebo alespoň nějaký návod. :smile: 
https://trello.com/c/ZhomW1qZ/467-2-p%C5%99idat-mo%C5%BEnost-slevy-do-adminu
> Připsané slevy

- model/funkce/fw-database.php
Často se mi na lokále stává, že stránka padne na `Warning: Cannot modify header information - headers already sent by...`. Může za to persistentní připojení k databázi, které po chvíli nepoužívání databáze ukončí a nové spojení nejdříve zahlásí timeout a pak se bez problémů připojí.
Řešení je prosté, potlačil jsem warning při připojení k databázi. Případné jiné problémy jsou odchyceny vzápětí a reportovány včetně detailů jako Exception.
> Dlouho neaktivni spojeni k DB neposle HTTP headers kvuli warningu

- admin/scripts/modules/uvod.php
Občanský průkaz jsem skryl z adminu. Ověřoval jsem pak, že na tom nespadne editace uživatele (op nesmí být v DB null), což je samozřejmě OK, protože to se nemění.
Ale co nechápu je, že když se člověk registruje, tak se několik NOT NULL hodnot vůbec nepošle, například `op` a stejně se to uloží. Když tu samou query pustím přímo, tak to spadne. Zřejmě je v Gameconu zaplá nějaká MySQL direktiva, kterou neznám.
> Cislo obcanskeho prukazu skryto v adminu

- model/uzivatel.php
- web/moduly/registrace.php
Uživatelská data ukládáme do session prohlížeče, což je nepříjemné, protože když se data bez vědomí prohlížeče změní (v jiném prohlížeči, přes admin...) tak každý prohlížeč pak ukazuje jiná, ta "svoje" data.
Oprava je v tom, že přenačtu uživatelská data z databáze vždy, když je někdo chce.
Přišel jsem na to při práci na https://trello.com/c/LMovvQif/785-chyba-v-p%C5%99ihla%C5%A1ov%C3%A1n%C3%AD-%C5%BEensk%C3%A1-mu%C5%BEsk%C3%A1-m%C3%ADsta
> Uzivatel je na webu vzdy prenacten, aby data v session nezastarala

- model/uzivatel.php
- web/index.php
Opravena chyba z https://github.com/gamecon-cz/gamecon/pull/91, kdy jsem obnovoval uživatelská data v session vždy, což ale rozbilo výběr uživatele v adminu.
Teď se uživtelská data v session obnovují jen na webu.
> Uzivatel lze v adminu nacist

- web/moduly/registrace.php
- web/soubory/styl/styl.less
Ted je na webu při registraci a editaci údajů povinný formát data bez mezer, tedy d.m.Y, což je dost nepříjemné obzvlášť při editaci, kdy uživatel edituje třeba jen pohlaví, ale my mu do formuláře vyplníme jeho datum narození ve formátu s mezerami. Takže to při každém uládání změn vyžaduje ruční opravu formátu data narození.
Upravil jsem to tak, aby mezery mezi dnem, měsícem a rokem byly jedno.
Přišel jsem na to během práce na https://trello.com/c/LMovvQif/785-chyba-v-p%C5%99ihla%C5%A1ov%C3%A1n%C3%AD-%C5%BEensk%C3%A1-mu%C5%BEsk%C3%A1-m%C3%ADsta
> Pri registraci lze pouzit datum narozeni s mezerami mezi dnem mesicem a rokem

- web/index.php
Opraven crash na webu, když uživatel není přihášen `Call to a member function otoc() on null`
Chyba zanesena s https://github.com/gamecon-cz/gamecon/pull/93
> Web nepadne na fatal kdyz uzivatel neni prihlasen

- model/uzivatel.php
Pokud uzivatel zvoli pri prihlaseni "zapamatovat" tak je prihlasen i po vyprseni PHP session.
Moje chyba, kvůli přenačítání dat o uživateli jsem použil funkci `otoc`, která volá `odhlas`, což ale dohlašuje jako kdyby na to kliknul uživatel, tedy smaže to i cookie, která má udržet uživatele přihlášeného celý rok.
> Přihlášení "zapamatovat" platí i po vypršení PHP session

- admin/scripts/modules/uvod.xtpl
Kdykoliv se změnila velikost okna s obsahem v adminu - Úvodu, tak se javascriptem přeskládaly sloupce s obsahem. Na mobilu se to pak stalo pokaždé, když někdo kliknul do vstupního pole, protože se otevřela virtuální klávesnice, to změnilo velikost okna, to přeskládalo obsah a to na mobilu znamená ztrátu focusu, takže se klávesnice zase zavřela.
Teď se sloupce přeskládají pouze pokud to má smysl, tedy pokud se změnila velikost okna natolik, že je tam o místo na celý sloupec víc nebo míň (a ne při každém pixelu).
https://trello.com/c/HbOrowU4/793-editace-v-adminu-na-mobilu
> Prave zobrazena klavesnice neni zase skryta kvuli prekresleni sloupcu v admin Uvodu

- migrace/055.php
https://trello.com/c/PydmpjQ9/710-vymazanie-osobn%C3%BDch-%C3%BAdajov
Oprava následujícího:
- vstupní parametr se jmenoval stejně jako sloupec ve `WHERE`, takže to MySQL nepochopilo (MySQL ignoruje velikost písmen téměř pro vše https://dev.mysql.com/doc/refman/8.0/en/identifier-case-sensitivity.html, takže `id_uzivatele` je pro něj to samé jaké jako `ID_UZIVATELE`, což ve výsledku anonymizovalo všechny uživatele, protože `id_uzivatele` se vždycky rovná samo sobě)
- většina položek nemůže být null, nýbrž pouze prázdný string
- takže se anonymizovalo jen `ubytovan_s` a `skola`
- `DATE_FORMAT(datum_narozeni, '%y-00-00')` zblbne MySQL natolik (kvůli nulovému měsíci a dnu), že z toho vznikne `2066-01-01`
PS: raději bych viděl tuhle logiku v PHP a měl v adminu červené tlačítko *Anonymizovat*
- …
> Fixed anonymization of user data according to GDPR

- admin/index.php
- admin/templates/paticka.xtpl
Před časem jsme došli k tomu, že funkci na nahlašování bugů v adminu nikdo nepoužívá, protože to každý hlásí svému nadřízenému, až se to nakonec dostane na IT.
Takže hlášení bugů z adminu jakožto mrtvý kód odstraňujeme.
https://trello.com/c/sYqwgsHT/798-z-adminu-lze-z%C5%99ejm%C4%9B-odeslat-nahl%C3%A1%C5%A1en%C3%AD-bugu-bez-n%C3%A1zvu-a-bez-textu
> Removed unused bug report from admin

- composer.json
- composer.lock
- migrace/062.php
- migrace/pomocne/062/062_opravene_kategorie_sjednocenych_tagu.csv
- migrace/pomocne/062/checkNameUniquenessFunction.php
- migrace/pomocne/062/fetchCategories.php
- migrace/pomocne/062/fetchTags.php
- migrace/pomocne/062/intToSqlValuesFunction.php
- migrace/pomocne/062/removeDiacriticsAndToLowerFunction.php
- model/vyjimkovac-chyba.php
- nastaveni/.gitignore
https://trello.com/c/dFzCulIR/846-n%C4%9Bkter%C3%A9-%C5%A1t%C3%ADtky-chyb%C3%AD
Loni jsem pokazil sjednocování štítků, když jsem změnil název některých kategorií jen ve zdrojovém souboru se štítky, ale už ne v souboru s kategoriemi samotnými, takže se najednou rozcházely názvy "deskovky" a "desk" a tím se některé štítky nahrály bez kategorie. A tím se také přestaly zobrazovat.
Zkopíroval jsem původní SQL migraci, opravil názvy kategorií, přidal NOT NULL kontrolu ke kategorii každého štítku, aby mi zase nějaký neutekl bez kategorie a ve finále jsem nahradil loňská data za opravená.
Riziko je, že tím přepíšu změny ve štítcích, které za ten rok někdo udělal. Poslal jsem dotaz na Smauga, zda je to OK.
> 846: Oprava štítků, aby každý patřil do nějaké kategorie

- admin/scripts/modules/aktivity/aktivity.php
Ve filtru aktivit https://admin.gamecon.cz/aktivity  _Zobrazit jen_ chybí jejich názvy . Tohle to opravuje.
> Oprava zobrazení názvu typu aktivity ve filtru

- admin/migrace.php
- model/funkce/fw-database.php
- nastaveni/nastaveni-local-default.php
Jelikož nováčci mají často potíže s nahozením MySQL a připojením se k databázi, tak jsem nahodil veřejně dostupnou anonymizovanou databázi. Ale raději na nestandardním portu, aby mi to nebombardovaly roboti.
Tohle přidává podporu nestandardnímu MySQL portu do Gameconu.
> Lze zadat port pro připojení k DB

- .github/workflows/run-tests.yml
- .gitignore
- composer.json
- composer.lock
- udrzba/_pomocne.php
- udrzba/ftp-deployment.php
- udrzba/nasad.php
V https://github.com/gamecon-cz/gamecon/pull/145 jsem zprovoznil Unit testy s poslední verzí testovací knihovny. A abychom ty testy mohli pouštět i lokálně (doteď se pouštěly jen v rámci Github Actions), tak jsem tu knihovnu nechal v require dev.
Jenže tím se začala tahle knihovna (a spousta dalších, na kterých je závislá) kopírovat na servery při deploy.
Upravil jsem proto nastavení FTP deploy, aby se tyhle knihovny přeskočily a přitom jsem rovnou zaktualizoval i knihovnu FTP deploy, abych si byl jist, že návod který pro to čtu na stránkách knihovny, platí.
Tím ale vyskočila chyba v nové verzi knihovny, kdy nefungovalo přímé volání z CLI, takže jsem musel přidat náš vlastní loadovací skript.
> Přeskočit knihovny pro unit testy při kopírování souborů do produkce

- model/chyba.php
https://trello.com/c/XNY4iItG/438-nov%C3%BD-web
Jelikož jak backendisti, tak i frontendisti hrabali ve stejný čas do stylu hlášek, tak nakonec se na webu kladné hlášky zobrazovaly jako chyby.
Tohle to opravuje.
> 438: Oprava stylu kladné hlášky pro web

- model/Vyjimkovac/Vyjimkovac.php
- web/index.php
- web/sablony/blackarrow/index.xtpl
Při práci na https://trello.com/c/Uxmm2f8V/802-p%C5%99edm%C4%9Bty-v-shopu-2021 jsem zjistil, že když mi to padne na JS chybu, tak v "Chybách" v adminu není ani čárka.
Je to tím, že na webu už nepoužíváme jQuery a logovač na něj spoléhá.
Tohle upravuje JS logovač, aby nevyžadoval jQuery a aby se opět logovali JS chyby z webu.
> 802: Na webu se opět logují JS errory do SQLite

- nastaveni/nastaveni.php
Měli jsme nastavený začátek na 15. 7. 2021, jenže to je čtvrtek a technické aktivity začínají už ve středu.
> 841: Oprava začátku Gameconu posunutím data

- web/moduly/aktivity.php
https://trello.com/c/fyNAyXKZ/859-nefunguje-detail-vyprav%C4%9B%C4%8De
Kvůli recyklaci stránky pro aktivity na zobrazení vypravěče a jeho aktivit nebyly některé proměnné nastavené a pak to padalo na fatal.
> 859: Fix: detail vypravěče nepadne na fatal

- composer.json
XTemplate závislost máme nešťastně určenou v composer.json přes `"godric/xtemplate": "dev-master"`, tak nám jeho změny lítají dovnitř kompatibilita nekompatibilita.
A Godrik nedávno XTemplate změnil a najednou to očekávalo stejný název souboru, ale s jiným obsahem a cache tak najednou byla neplatná, XTemplate to nepoznal a crashlo to.
Tímhle cache promažeme vždy, když se zavolá composer install nebo update.
Pozor! Není to finální a zakládám na to [task](https://trello.com/c/C8SqPoi0/793-zm%C4%9Bna-v-xtemplate-n%C3%A1m-m%C5%AF%C5%BEe-hodit-fatal) - tohle se nám klíďo píďo může stát v podukci.
> Cache šablon se při změně knihoven zahodí

- model/fio-platba.php
- tests/Model/FioPlatbaTest.php
https://trello.com/c/mF1tzIMP/855-sp%C3%A1rov%C3%A1n%C3%AD-sk-plateb
Ze Slovenska posílají platby s variabilním symbolem ve zprávě. Ten by měl být ve formátu `/VS/123456`, ale občas to pošlou bez úvodního lomítka.
Budeme parsovat i takový formát.
> 855: Spárujeme i platbu s VS v textu bez lomítka na začátku

- migrace/058.php
- migrace/060.php
- migrace/062.php
- migrace/064.php
- migrace/065.php
- migrace/071.php
Stalo se, že jsme se Kubou sekli na několik dní při nahazování jeho lokální kopie kvůli nefunkčním cizím klíčům.
Důvodem bylo, že jeho databáze neměla jako výchozí engine InnoDB a protože některé migrace engine výslovně neuváděly, tak se pak tabulky vytvořili s MyISAM a MySQL zahlásilo svůj oblíbený neurčitý error, který může znamenat půlku vesmíru.
Tímto ve všech migracích výslovně uvádíme engine InnoDB, aby se to dalšími nováčkovi nestalo.
> Upraveny migrace aby bylo vzdy pouzito InnoDB

- model/finance.php
https://trello.com/c/23zOhWln/250-zm%C4%9Bny-v-adminu-2021
Jelikož nepotřebujeme vidět _Stav účtu: | 2.8421709430404E-14 Kč_ a navíc je to chyba při sčítání float v PHP, tak budeme zůstatek zaokrouhlovávat.
> 250: Zaokrouhlovat zůstatek na účtu kvůli potížím s float ocintky

- admin/scripts/modules/uvod.php
- admin/scripts/modules/uvod.xtpl
- model/program.php
- Aby mohl infopult prodávat více kusů naráz, jelikož naklikávat po jednom dvacet kostek je fakt opruz
- Aby se zobrazoval celý příliš dlouhý název aktivity v programu alespoň jako title po najetí myši
- Aby se Rychloregistrace v adminu ukazovala jen když není vybrán pracovní uživatel
> Možnost prodat více kusů naráz

- model/platby.php
https://trello.com/c/zsb8bCet/884-nepropsan%C3%A1-platba-do-adminu
I letos se stalo, že jedna platba ani po týdnu nebyla propsána do Gameconu. Ruční spuštění synchronizace s rozšířeným záběrem synchronizovaných dní ale platbu stáhlo. Zřejmě tedy jeden týden zpětně nestačí.
> 884: Stahovat platby z Fio pro spárování podle VS až třicet dní zpět

- web/moduly/titulka.php
- web/sablony/blackarrow/titulka.xtpl
- web/soubory/blackarrow/gchlavicka/gchlavicka.less
https://trello.com/c/WwMmnO6l/902-zm%C4%9Bnit-form%C3%A1t-data-na-webu
Uživatele ten náš bordel se začátkem Gameconu mate. Přidáme zatím aspoň na titulku rok, pro který to datum platí.
> Titulka zobrazuje datum Gameconu včetně roku

- model/funkce/fw-database.php
Hodnoty pro databázi jsme měli prehistoricky ošetřené nedostatečně. Teď to necháme přímo na databázi.
> 562: Hodnoty pro MySQL escapuje přímo MySQL

- admin/files/design/styl.css
- admin/index.php
- admin/scripts/admin-menu.php
- admin/scripts/modules/aktivity/aktivity.php
- admin/templates/prihlaseni.xtpl
Aby měla Cemi radost, že v levém hlavním menu Adminu je Aktivity, ale v submenu je pak položka nazvaná jako Přehled aktivit... trochu kouzlení s CSS
> submenu pomoci CSS zobrazi custom-text Prehled aktivit namisto Aktivity

- admin/scripts/modules/aktivity/prihlaseni-drd.php
Aby dostal i PJ email o tom, že družina, kterou vedl, nepostoupila a on se pak na chodbě nedivil, proč potkává její členy zádumčivé.
https://trello.com/c/q1Gdu1lG/888-mdrd-hromadn%C3%A9-informov%C3%A1n%C3%AD-dru%C5%BEin-o-nepostupu
edit: Tohle byl trochu chaos, ve finále tahle změna jenom sjednocuje formát zápisu v kódu.
> Mdrd mass emails

- model/SystemoveNastaveni/SystemoveNastaveni.php
https://trello.com/c/jtDu0OoQ/926-zm%C4%9Bny-bonus%C5%AF#comment-
Jelikož 280 / 3 není chtěných 70, ale nechtěných 93...
Oprava bonusu vypravěče za hodinovou aktivitu.
> 926: Oprava vypočteného bonusu za hodinovou aktivitu

- model/funkce/funkce.php
Vyměnit HTTP_HOST za SERVER_NAME, který je vždy bez portu, jinak
nefunguje validní POST požadavek s portem v adrese.
> Fix: $referrerHost neobsahuje číslo portu HTTP_HOST ano

- admin/scripts/zvlastni/reporty/update-zustatku.php
- model/uzivatel.php
https://trello.com/c/d7D6GeD1/286-odhl%C3%A1%C5%A1en%C3%AD-z-gc-p%C5%99evod-pen%C4%9Bz-do-dal%C5%A1%C3%ADho-ro%C4%8Dn%C3%ADku
Stává se, že si někdo pošle peníze na GC, pak včas ohlásí, že nemůže a my ho z GC odhlásíme. Jenže to provedeme tak, že mu sebereme roli "Přihlášen na GC rok XY". A při překlápění ročníku jsme tyto přeskakovali, takže jim finance zmizely.
> 286: Při překlápění ročníku převádíme zůstatky všem i když nedorazili na GC

- admin/cron.php
- backup/db/.gitignore
- nastaveni/nastaveni-local-default.php
- nastaveni/nastaveni-local-docker_default.php
- nastaveni/nastaveni.php
Návrh na úpravu zálohy DB
1. Konstanta s adresářem pro zálohy databáze je definována jen pro produkci, jinde není potřeba
2. Adresář pro zálohu databáze je přesunut mimo adresář s cache, protože cache je čas od času nemilosrdně promazána a to u záloh DB nechceme
3. Když konstanta s adresářem pro zálohy DB chybí nebo je prázdná, tak CRON task nepadne na exception, pouze problém ohlásí a pokračuje
> 578: Samostatný adresář pro zálohu databáze

- admin/cron.php
- backup/db/.gitignore
- nastaveni/nastaveni-local-default.php
- nastaveni/nastaveni-local-docker_default.php
- nastaveni/nastaveni.php
Kopírování na FTP stejně nefunguje, takže lze vypustit FTP modul. Zálohy
nejsou pojmenované náhodným jménem, ale dle času, aby se daly později
rozumně použít. Složku pro ukládání záloh je nutné nastavit konstantou.
Pro správnou funkci cronu je potřeba nastavit `ZALOHA_DB_SLOZKA`,
konstanta `FTP_ZALOHA_DB` se stala zbytečnou.
> 578: Zálohuj databázi do definované složky a s rozumným jménem

- admin/scripts/modules/nastaveni/nastaveni.php
- admin/scripts/modules/statistiky.php
- model/Statistiky/Statistiky.php
- nastaveni/nastaveni.php
> Bylo by možný nastavit jako default, že se to zarovnává na začátek registrací? Takhle to musím furt překlikávat, protože zarovnání na konec GC mi je k ničemu, když ta letošní křivka ještě nedoběhla. Případně aby se to zarovnávalo pro předpokládaný konec GC a ne pro konec grafu, teď když si to zarovnáš pro konec GC, tak letošní křivka nesedí, protože bere jako konec GC dnešek.
Bylo
> 876: Statistiky právě probíhajícího ročníku jsou protaženy až do konce GC

- migrace/2022-07-11_01-datum-pro-ukonceni-registrace-na-gamecon.php
- model/SystemoveNastaveni/SystemoveNastaveni.php
https://trello.com/c/AaHUnSdx/976-%C3%BApravy-v-e-shopu-2022-3#comment-62cf1865832dd571df983b0a
Nějak se nemůžeme rozhodnout, zda chceme povolit registraci přes web až do konce GC.
Tak na to udělám nastavení.
> 976: Přidána možnost změnit konec registrací přes web

- udrzba/borg/borg_mount_backup.sh
Abychom mohli lokálně získat zálohu databáze z Borgu pro zvolené datum, například
`./borg_mount_backup.sh 2023-01-07`
> Skript pro snazší mountování zálohy z Borgu pro zadané datum

- admin/files/keep-scroll-on-reload-1.2.js
- admin/scripts/modules/aktivity/aktivity.xtpl
Nedávno jsme JS funkci na udržení scrollu mezi přenačtením stránky přesunuli, ale zapomněli jsme změnit její volání.
> Opraveno udržení scrollu po akci na stránce admin aktivit

- model/Web/Loga.php
- web/index.php
- web/moduly/sponzori.php
- web/moduly/titulka.php
- web/sablony/blackarrow/sponzori.xtpl
- web/tridy/modul.php
https://trello.com/c/cmAKkTlf/881-%C5%99azen%C3%AD-log-sponzor%C5%AF-a-partner%C5%AF-na-webu
Abychom mohli loga sponzorů a partnerů seřadit jak potřebujeme.
Nově to lze seznamem v souboru RAZENI.csv v adresáři s obrázky a předponou `číslo_`.  Řazení v souboru má přednost.
> 881 řazení log sponzorů a partnerů na webu

- admin/scripts/zvlastni/reporty/zazemi-a-program-potvrzeni-pro-navstevniky-mladsi-patnacti-let.php
https://trello.com/c/HRzR7ccv/1108-oprava-report%C5%AF#comment-6555442fbf0691ec8c85181c
> potvrzení pro mladší 15 let vypisuje i rychloregistrace a SYSTEM, asi by bylo pohodlnější, kdyby tam nebyly, vzhledem k tomu, že to očividně zobrazuje všechny kdy registrované mladší 15 let, ne jen letošní
> Neexportovat SYSTEM a uživatele z rychloregistrace bez změněného data narození

- migrace/9999_01-letosni-role-krome-ucasti-endless.php
Př překopení ročníku a spuštění migrace se sice přejmenovaly staré ročníkové role a vytvořily nové, ale k novým se ze starých nepřenesla práva.
> Fix přenosu práv ze starého ročníku do nových ročníkových rolí

- web/sablony/blackarrow/prihlaska.xtpl
https://trello.com/c/l4JkQQWB/1188-chyba-ubytov%C3%A1n%C3%AD-s-tematikou-gameconu
> 1188 Oprava matoucího textu v přihlášce o tématickém ubytování

- model/Aktivita/Aktivita.php
- model/Aktivita/Program.php
Zároveň s tímhle PR je potřeba posunout na všech aktivitách na začátku programu den o 1 dopředu
řeší [Trello kartu](https://trello.com/c/MKAUG6BZ/1196-mdrd-semifin%C3%A1le-a-fin%C3%A1le-se-%C5%A1patn%C4%9B-zobrazuj%C3%AD-v-programu)
> oprava den aktivity podle `PROGRAM_ZACATEK`

- migrace/2024-06-16-opravit-tymove-limity-kapacity.php
- model/Aktivita/Aktivita.php
- model/Aktivita/SqlStruktura/AktivitaSqlStruktura.php
- model/tym.php
Oprava verze 2, teď už by měla fungovat spolehlivě i s instancovanými aktivitami. Je to nepěkné, ale funkční řešení.
> 1213 při znovuuložení týmových aktivit se resetuje počet míst

- admin/scripts/zvlastni/reporty/report-infopult-ucastnici-balicky.xtpl
pro gandalfa; mění tisk na pouze jednosloupečkový místo dvousloupečkového protože docházelo ke zbytečnému kontraproduktivnímu zalamování řádků
> fix zobrazování balíčků k tisku

- .github/workflows/run-tests.yml
Odstraňuji předchozí pokus o spuštění testů za každou cenu, protože spuštění testů po auto-rebase vyřešil fine-grained access token (protože výchozí GITHUB_TOKEN schválně pouští jen jednu action, ale už nedovolí navazující).
> GitHub autorebase

- .docker/docker-build.sh
v rámci rozšíření inkluzivity specifického HW využívaného zejména ovcemi (Apple) potřebujeme buildovat image i pro arm v8 procesory (i další procesory kdyžuž - třeba mini lokální GC na RPi by se mohl někdy v budoucnu hodit jako záloha pro infopult) 
nutno zkontrolovat že při buildu se zobrazí pak pushnuté arm i amd verze na docker hubu [gameconcz/gamecon](https://hub.docker.com/r/gameconcz/gamecon/tags)
> arm procesory

- admin/scripts/zvlastni/reporty/duplicity.php
- navrhuji jednoduché uvozovky v SQL query, protože pro čtenáře zvyklé na PostgreSQL to pak nevzbuzuje falešný dojem že jde o identifier.
- navrhuji lokální proměnnou `$u` přejmenovat na `$u1`, aby nepřepisovala globální proměnnou $u (právě přihlášený uživatel) a aby názvem více patřila k druhé proměnné `$u2`
> 1283 Refaktoring podle konvencí stařešinů
